### ISSUE TITLE
Message statistics

### ISSUE THREAD

**Issue by chlarsen** [jasonmunro/cypht#118]
Dear Jason,
It is great to have those new indicators of new (unread) messages per folder and per screen lot. However, I think the calculation is not yet quite right:
For instance, in a folder with 150 new messages, it gives me 20  as indicator next to the mail folder name, because 20 was also the "Max messages per source" setting - is if it could not see beyond the rim of the "Max messages per source" field.
Am I missing something? Thanks a lot,
Chris

**Comment by jasonmunro** [comment]
weird. The unread indicator next to the "unread" combined page is limited by the max_per_source (which I just bumped to 1000), but the indicators next to the folders themselves in the "email" section of the folder list should be correct. They are taken from the IMAP STATUS command on the mailbox, which returns a total number of unread for that folder. They are correct for my accounts.
