### ISSUE TITLE
install script creates subfolder

### ISSUE THREAD

**Issue by jult** [jasonmunro/cypht#121]
The bash script you posted here https://cypht.org/install.html creates a `/usr/share/cypht/cypht-master/` dir, and then subsequently everything you mention later on on that page does not compute;

    cd /usr/share/cypht  (or wherever you put the code in section 1)
    sudo php ./scripts/config_gen.php

There's no ./scripts there.

    sudo ln -s /usr/share/cypht/site /var/www/html/mail

There's no /cypht/site dir..

Just sayin'..

**Comment by jasonmunro** [comment]
Thanks for the feedback! Just fixed the script:

This:
sudo mv cypht-master $DESTINATION

Should be this:
sudo mv cypht-master/* $DESTINATION
