### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by esud** [jasonmunro/cypht#123]
I installed Cypht on my server (Nginx, PHP7, Mysql). I also can access the login-screen in a browser. However, I can not login. When I input username and password and click "Login", then the input fields will be cleared and nothing happens. There is no error message. I tried many different configurations of auth_type. Everytime is the same result. 

Is there any possibility to check the exact reason? Or any other suggestions?

**Comment by jasonmunro** [comment]
We can surely track down the issues here. First thing to do is make sure you are running in debug mode. Then when you try to login, check the PHP error log. Cypht outputs a ton of useful information, especially about failed logins, when in debug mode. To run Cypht in debug mode, you simply access the main directory's index.php file. To run in production mode, you access the index.php file in the "site" subfolder. Hope that helps! Happy to keep debugging if you run into more issues.

Since you mention Mysql, and there is no "invalid username/password" message, I suspect there is some issue connecting to the DB, or accessing the required tables. Debug mode should provide a clue!

**Comment by esud** [comment]
I get following debug info:
2016/10/01 22:49:12 [error] 249#249: *33 FastCGI sent in stderr: "PHP message: Array
(
    [0] => Using Hm_DB_Session with Hm_Auth_DB
    [1] => Using DB user configuration
    [2] => Using sapi: fpm-fcgi
    [3] => Request type: HTTP
    [4] => Request path: /
    [5] => TLS request: 0
    [6] => Mobile request: 0
    [7] => Page ID: home
    [8] => Connecting to dsn: mysql:host=127.0.0.1;dbname=mail2
    [9] => Setting cookie: name: hm_id, lifetime: 0, path: /, domain: mail, secure: , html_only 1
    [10] => Setting cookie: name: hm_session, lifetime: 0, path: /, domain: mail, secure: , html_only 1
    [11] => Handler module Hm_Handler_load_feeds_from_config activated but not found
    [12] => Redirecting to /
    [13] => PHP version 7.0.11
    [14] => Zend version 3.0.0
    [15] => Peak Memory: 4096
    [16] => PID: 53
    [17] => Included files: 58
)" while reading response header from upstream, client: 192.168.0.3, server: mail, request: "POST / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mail", referrer: "http://mail/"
2016/10/01 22:49:12 [error] 249#249: *35 FastCGI sent in stderr: "PHP message: Array
(
    [0] => Using Hm_DB_Session with Hm_Auth_DB
    [1] => Using DB user configuration
    [2] => Using sapi: fpm-fcgi
    [3] => Request type: HTTP
    [4] => Request path: /
    [5] => TLS request: 0
    [6] => Mobile request: 0
    [7] => Page ID: home
    [8] => Handler module Hm_Handler_load_feeds_from_config activated but not found
    [9] => TRANSLATION NOT FOUND :Cypht:
    [10] => PHP version 7.0.11
    [11] => Zend version 3.0.0
    [12] => Peak Memory: 4096
    [13] => PID: 54
    [14] => Included files: 59
)" while reading response header from upstream, client: 192.168.0.3, server: mail, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mail", referrer: "http://mail/"

> I suspect there is some issue connecting to the DB

I don't thing so, because I created an user using php script and this user entry was successfully created in the database.

**Comment by jasonmunro** [comment]
thanks for the follow up. You are right, DB access looks good, and it looks like you are being authenticated, so I'm not sure whats going wrong. The cookie domain is being set to "mail", is that the hostname you are using to access Cypht? If not, you can force the correct hostname for cookies with the cookie_domain setting in the hm3.ini file.

**Comment by esud** [comment]
> The cookie domain is being set to "mail", is that the hostname you are using to access Cypht?
Yes, it is a local domain which is resolved via /etc/hosts

So, but now I found the problem. When I open Cypht with Midori (Version 0.5.11 on Arch Linux) then the login not works as described above. But when I open it with Firefox then it works without problems. 

Of course we need to check why exactly it not works with Midori. In general I prefer to use Midori because it is a lightweight browser.

**Comment by jasonmunro** [comment]
Interesting! Looks like Midori is available in Debian Sid (my preferred distro). I will install it and see if I can get things sorted.  Thanks for figuring this out! I want Cypht to work with as many browsers as possible (within reason), so this is great feedback that helps make the project better.

Thanks again!

**Comment by jasonmunro** [comment]
Just gave Midori a try with my test setup and I was able to login without issue. I will keep digging and let you know.

**Comment by jasonmunro** [comment]
I walked through the Midori settings, not seeing anything obvious that might cause Cypht to not work on login. I used it for a while (thanks for mentioning it, it's cool!). but have not had any issues logging in. or staying logged in. Any thoughts?

**Comment by esud** [comment]
Yesterday I researched a little about this problem. It looks like Midori can not store cookie which is initialized in framework.php file. So, when you e.g. disable the setcookie function, you will get the same behavior at the login. But right now I don't know why exactly Midori can not store this cookie. Cookies from another webpages works without problems. I will research more about it when I have more free time.

**Comment by esud** [comment]
Ok, I found the problem. I use this application only on my local server. So, I use the Domain "mail". But the Midori-browser refuse to set the cookie because the domain must contain at least two dots (.)

So, to fix this problem I replaced the line 
return setcookie($name, $value, $lifetime, $path, $domain, $secure, $html_only);
with
return setcookie($name, $value, $lifetime, $path, '', $secure, $html_only);

**Comment by jasonmunro** [comment]
I just pushed a change to help out with this. In your hm3.ini, you can now set the "cookie_domain" option to the string "none", and it should accomplish the same thing as your code change above. If you get a chance to test it out, that would be great! Thanks.

**Comment by jasonmunro** [comment]
Looks like I missed a few places where cookie_domain is used that I need to fix. Correcting that now!

**Comment by jasonmunro** [comment]
Should be all fixed up now.

**Comment by jasonmunro** [comment]
with the ability to set the cookie domain I think this should be closed. If you disagree, feel free to re-open :) Thanks again for the feedback.
