### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by jesusaplsoft** [jasonmunro/cypht#126]
Add reCaptcha to login form

**Comment by jasonmunro** [comment]
I think this will be pretty easy to build as a module set. Great idea, thanks for the suggestion! I will try to get something built this week.

**Comment by jasonmunro** [comment]
The initial version is committed.It "works for me", but I wouldn't be surprised to find bugs. When you can, give it a try, and let me know how it goes!

**Comment by jasonmunro** [comment]
I'm using this on a couple test sites and not having any issues. I'm going to close this now since it's "done". If you give it a try and have problems feel free to open a new issue
