### ISSUE TITLE
Special use folder support (Sent, Drafts, Trash)

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#128]
It would be nice to support special use folders:
- Save outbound mail in Sent
- Save a draft in Drafts
- Move to Trash on delete

**Comment by jasonmunro** [comment]
Preliminary support for saving outbound messages in a sent folder is pushed. This only works for IMAP servers that support the special use mailbox extension for now. We still need to provide tools for people to set custom special use folders

**Comment by jchevali** [comment]
When I send an email, it appears to be saved to both the Inbox and the Sent folder.

**Comment by jasonmunro** [comment]
Custom Sent and Trash folders are now supported! These can be configured in the folders page in the settings section for each configured imap server. If the trash folder is not configured for specific account, deleting a message is permanent. When sending a message, the imap account associated with the sending profile will be used to save the copy to the defined folder. If no profile is used no sent copy is saved.

**Comment by jasonmunro** [comment]
Support for saving drafts is in process. The UI to setup your draft folder is done, but the current draft system (session level), does not support it yet.

**Comment by justinvoelker** [comment]
Though an old, mostly resolved issue, I'm having trouble with sent items not being saved to their appropriate sent folder I set up both Trash and Sent as special folders. Trash is working, Sent is not. Any thoughts on why it wouldn't work or has there been any recent changes to this functionality?

**Comment by ulfgebhardt** [comment]
Had the same issue, solved it by removing the option "Site > Always BCC sending address".
If a Sent Folder is configured the Mail is saved there on my installation.

**Comment by dumblob** [comment]
@jasonmunro is the option "Site > Always BCC sending address" by default enabled? If so, then I would vote for making it disabled by default as most if not all IMAP servers support special folders and these shall have priority over the "Inbox" solution.

**Comment by justinvoelker** [comment]
The "Always BCC sending address" setting is already unchecked for me. @dumblob I did not change that value so it appears to be defaulted that way.

**Comment by almereyda** [comment]
As Sent and Trash are working, I suggest to close this issue and reopen a new one about the missing bits of logic for a complete Draft system.

Other issues about *always BCC sending address* may follow the prior example.

**Comment by jasonmunro** [comment]
@almereyda good catch. This also happens on the move and copy dialogs. I will create a new issue for that, and a new issue for draft support, and close this one. Thanks for the feedback!
