### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by jmce** [jasonmunro/cypht#136]
For issue reporting, it might be convenient to have a version number — the current alternative (when fetching master.zip according to the installation instructions) is to mention the common datetime of the extracted files.

**Comment by jasonmunro** [comment]
agreed :) At some point we need to start tagging and doing releases as well.

**Comment by jasonmunro** [comment]
I'm now maintaining a version number as a comment in the index.php file. Unlike CVS/SVN, there is no good way to automatically embed a version in a comment (it is possible, but hacky and of questionable worth). Before I make a commit, I run a script to make sure I don't have any left over debugging. This script now bumps the "GIT VERSION" value with "git rev-list --all --count".

Until we get to a real release point, this should help!
