### ISSUE TITLE
Failure to create folders 

### ISSUE THREAD

**Issue by jmce** [jasonmunro/cypht#138]
With cypht configured for IMAP access to a dovecot server (→ version info at the end),
I was unable to create new folders (both at the top and under pre-existing folders),
getting the following nginx error log entry (edited to change server domain and client IP address to example values)

> 2016/10/15 00:30:25 [error] 23418#23418: *1 FastCGI sent in stderr: "PHP
message: PHP Warning:  Missing argument 3 for Hm_IMAP_List::get_cache(),
called in /opt/jasonmunro/cypht/share/modules/imap_folders/modules.php
on line 23 and defined in
/opt/jasonmunro/cypht/share/modules/imap/hm-imap.php on line 42
> PHP message: PHP Fatal error:  Call to a member function get() on
integer in /opt/jasonmunro/cypht/share/lib/cache.php on line 216" while
reading response header from upstream, client: 192.0.2.33, server: mail.example.com,
request: "POST /?page=folders&imap_server_id=1 HTTP/2.0", upstream:
"fastcgi://unix:/var/run/php5-fpm.sock:", host: "mail.example.com",
referrer: "https://mail.example.com/?page=folders&imap_server_id=1"

#### Version info:
cypht master.zip files from 2016-10-12 14:48:18 +0000 on Debian Jessie [8.6] with
* memcached 1.4.21-1.1
* php-memcached 2.2.0-2
* nginx-… 1.9.10-1~bpo8+3
* php5-…  5.6.26+dfsg-0+deb8u1 (using php5-fpm)
* postfix-… 2.11.3-1
* dovecot-… 1:2.2.24-1~bpo8+1 [using sdbox as mailbox format]
* openssl-… 1.0.2j-1~bpo8+1
* libssl1.0.0  1.0.2j-1~bpo8+1

**Comment by jasonmunro** [comment]
Sorry about this. I changed the way we cache IMAP data, and failed to update this module set's calls to the method. Fixed in https://github.com/jasonmunro/cypht/commit/7ed6e4c263ba734da5fc155ed8a0b69c890196ef

**Comment by jasonmunro** [comment]
Since I'm pretty sure this is resolved I'm closing this issue. Feel free to re-open if it's still not working for you!
