### ISSUE TITLE
Support unix socket for database connection

### ISSUE THREAD

**Issue by Exagone313** [jasonmunro/cypht#140]
Hi,

That would be nice to support connection to database using a unix socket. To do that, you just have to add a boolean ini setting to have the choice between _host_ and _unix_socket_.

**Comment by jasonmunro** [comment]
I just pushed this out. I added 2 new ini file entries: db_connection_type (can be either "socket" or "host"), and db_socket which is used if the connection type is set to host. If you can give it a try that would be great! While I was looking at this code I realized that we should probably also add the ability to specify the port we connect to when using standard network connections. Should be easy enough to add. https://github.com/jasonmunro/cypht/commit/092afb52a3a5d72e2297ca93dffd359354cb6d99

**Comment by Exagone313** [comment]
I didn't install Cypht yet (please see the email I sent), but I will try it directly.

**Comment by jasonmunro** [comment]
No problem. I'm still getting caught up on my E-mail after being offline for a few days :) I will get back to you on that today.

**Comment by jasonmunro** [comment]
Using this now so I know it works :) feel free to re-open if you run into trouble.
