### ISSUE TITLE
PHP Notice:  Use of undefined constant VERSION

### ISSUE THREAD

**Issue by t-keller** [jasonmunro/cypht#141]
Hello,

I tried to create an account by calling:

`# php scripts/create_account.php toto toto`

But I got: 

`PHP Notice:  Use of undefined constant VERSION - assumed 'VERSION' in /usr/share/cypht/scripts/create_account.php on line 28`

I think it's related to a recent commit: https://github.com/jasonmunro/cypht/commit/87856c7c9e341409eb506b0f966926494128a645

Thank you

**Comment by jasonmunro** [comment]
Thanks for the feedback. I wanted to move the version def to the index file but I need to rethink that :) I will get this reverted.

**Comment by jasonmunro** [comment]
VERSION location is reverted so this warning should be gone

**Comment by t-keller** [comment]
Thank you ;)

**Comment by t-keller** [comment]
Good luck ;)
Can't wait to test the software.
