### ISSUE TITLE
Two Typos

### ISSUE THREAD

**Issue by manasb** [jasonmunro/cypht#143]
https://github.com/jasonmunro/cypht/commit/c8866dd4f1ed35d9e714cfeab9c942a9e048b269#commitcomment-19596385

**Comment by manasb** [comment]
Another typo

https://github.com/jasonmunro/cypht/commit/f9f422f3917b9f837bce65bc9fc53f0c90dc9861#commitcomment-19620323

**Comment by manasb** [comment]
I'm finding more and more things that I can contribute, I will have to set up a fork :)

**Comment by jasonmunro** [comment]
Much appreciated! These 2 are fixed. Feel free to add more to the issue, or create a pull request if you prefer. Thanks again!
