### ISSUE TITLE
wish list

### ISSUE THREAD

**Issue by dunstn** [jasonmunro/cypht#149]
Hi,

As I wrote in your blog, I'd like to ask for some new features/changes in Cypht:

1. The ability to configure the start page site-wise and on user level. I think, the current start page (Settings->Home) should appear the first time the user logs in. After that (or after he/she changed it), the Main->Everything page would be better, but it's even better if users can set their own start.

2. HTML mails should be displayed in HTML form instead of text form. 

3. Attachments should be separated from the message parts. Now the various parts of the message are mingled with the attachments in a list. It would be better to hide them, and show only attached files, preferably image types as thumbnails, other known filetypes as icons, etc. Sometimes it is necessary to see the message parts/message source, so a button to show/hide them would be nice.

4. (as it is written on the bottom of this text box: Attach files by dragging &  dropping.

Thanks
Bela Selmeci

**Comment by dumblob** [comment]
> preferably image types as thumbnails, other known filetypes as icons, etc.

I would prefer not showing thumbnails nor filetype icons etc. by default to stay mobile-friendly (size and rendering speed matters). Maybe this should be an option in user settings?

**Comment by jasonmunro** [comment]
@dunstn Thanks for reposting your ideas here. It's useful to have everything in the same place. Some thoughts on your suggestions:

- Adding a user option to setup the start page should be pretty easy (for main menu pages at least). I will see about getting that in the core module set. We already support a site wide default, check out the "redirect_after_login" setting in the hm3.ini file.

- yep, we should offer this, but I want to make sure it can be optional (I much prefer text only versions when I can). Should also not be too hard to do (Hastymail 2, my last client, supported it).

- I see the last suggestion as 2 new options: "simple attachments", and "thumbnails/icons" I like seeing the  full message structure (something most clients don't provide at all), but I realize it's not very user friendly. I like the idea of file type icons though (and I have no problem making those optional as well, or disabled on mobile even).

Thanks for the great feedback. I will reply to this issue when I have something for you to test!

**Comment by jasonmunro** [comment]
Suggestion #2 is done :) Now, by default, we will display the HTML message. The old behavior can be enabled with the "Prefer text over HTML when reading messages" option on the settings page

**Comment by dunstn** [comment]
Another suggestion:
An Edit button to the server settings. I can't modify the settings of an existing server.

Also, a log file would be great; I have sent a test mail which arrived successfully, but I can't find it in any of my Sent folders.

**Comment by conspacer** [comment]
Speaking of Sent folders @dunstn , it would be good to have the option somewhere to map which folder Cypht places copies of successful sent messages into by SMTP server (i.e. if sent by SMTP server 'X', store copy in IMAP/POP server 'Y', folder 'Z'). 
Some mail providers name those folders differently (Sent items, Outbox) plus language variations (Skickat, Gesendet).
Unfortunately I need to log into separate webmail clients to do a lot of my sending just to keep these things in order.

**Comment by jasonmunro** [comment]
@conspacer and @dunstn You are right, we need better special folder support (I opened an issue for this a while back). Some of the ground work for this is in place, but it needs a lot more work. Some IMAP servers support a "special folder" command that we can use to automatically determine the sent/trash/drafts folders (Gmail does, probably others) which is super helpful. the "Sent" combined view uses this to auto-discover Sent folders. We should still support the ability to assign whatever special folders per IMAP source you want.

In the meantime there is an option called "auto-bcc" in the General section of the site settings page. This will bcc the sending address with the outbound mail. It ends up in the inbox, but with a custom header so we can exclude it from the Unread view. I have also noticed that Gmail will automatically save a copy of outbound mail when using their SMTP server.

**Comment by jasonmunro** [comment]
@dunstn Can you elaborate for me what you mean by a "log file" ? In prior projects I had a logging plugin that would basically log every action taken by any user, but it sounds like maybe that is not what you mean?

**Comment by dunstn** [comment]
Thanks, but I found the necessary logs in the web server's and the mail logs. I think, however, that a separate log containing login, logout, sent message parameters for usage statistics would be useful, maybe as an option in the config file.

**Comment by dumblob** [comment]
> I think, however, that a separate log containing login, logout, sent message parameters for usage statistics would be useful, maybe as an option in the config file.

IMHO this is not a good solution. Better solution would be to provide a script (written in PHP to stay consistent with the rest of the repository and not require any other interprets/compilers), which would extract all the necessary information from standard locations (modifiable by [command line arguments](http://php.net/manual/en/features.commandline.php )) and produce a simple, but human-readable log on demand.

**Comment by dunstn** [comment]
Cypht is a multi-account email client, which can't access logs on the mail server. It would be better to create a logger plugin, that makes a human-readable log of configurable actions.

**Comment by dumblob** [comment]
@dunstn I misunderstood your initial description. A logger plugin makes sense.

**Comment by jasonmunro** [comment]
Have a couple updates on the original wishlist from this thread:
1. There is now an option to show a "simplified" message part structure, 
2. There is now an option to enable message part icons. Like all other icons these are inline data urls, so they  should not have any significant impact on performance.
3. I decided to also add a setting to control the icons (on the left) of message lists.These icons are now disable d by default.

All three new settings are in the site settings page -> general section.

Here is a screenshot of the message part section with icons.
![all_msg_parts](https://cloud.githubusercontent.com/assets/3793556/21370357/ec8d5826-c6d0-11e6-80e6-0ff922a18cf1.png)

and here is one with icons but a "simplified" message structure (same message as before).
![simple_msg_parts](https://cloud.githubusercontent.com/assets/3793556/21370363/f0d53bd8-c6d0-11e6-9ef2-7e490dafcf58.png)

Screenshots are done with "Ryan Finnie's MIME Torture Test v1.0" from 2003.

**Comment by dunstn** [comment]
Nice work!

**Comment by dumblob** [comment]
Really nice, thank you.

**Comment by dunstn** [comment]
I have a new suggestion: the Settings -> Folders menu would be more useful if displayed when the user clicks on a server's name in the Email list. Its present location is too far from the list it modifies.

**Comment by conspacer** [comment]
Great work @jasonmunro and a nice update with the message part icons.

**Comment by jasonmunro** [comment]
The original wish list from this issue is complete. There were a number of other suggestions in the comments that may or may not be done. It's hard to track this way, so if you had a suggestion in this thread you care about, please create a specific issue for it. Thanks!
