### ISSUE TITLE
Independent sending profiles

### ISSUE THREAD

**Issue by Pacien** [jasonmunro/cypht#152]
Hi!
It would be nice to be able to create profiles independently of incoming IMAP servers for sending emails with different identities, still linked to an outgoing SMTP server.

**Comment by conspacer** [comment]
Yes, the ability to attach multiple identity profiles to an SMTP server is important

**Comment by jasonmunro** [comment]
Profiles need a major overhaul. I coded up what I thought would be useful initially, but it's buggy and requires some more thought about the overall design and site specific implementation requirements.

**Comment by jasonmunro** [comment]
This is _finally_ added to the master branch (this will not be in the release code, it didn't make the cut). Some highlights:

- Backwards compatible with existing profiles. Once you update a profile, the new internal format is used from that point forward
- Profiles are not limited to one per imap/smtp server.
- You can create as many profiles as you want
- You can delete profiles
- A new profile requires a display name, E-mail address, Reply-to address, IMAP server, and SMTP server.

I'm going to close this out, if anybody runs into trouble or finds a bug, please open a new issue.

**Comment by conspacer** [comment]
Thanks @jasonmunro Ill be testing this out, will update if anything.

**Comment by jasonmunro** [comment]
@conspacer thanks for the testing - Feel free to re-open this issue or create a new one if you find anything amiss!

**Comment by jasonmunro** [comment]
@conspacer It just so happens I _just_ ran into a bug with this! We try to load legacy profiles and convert them to the new format, then if you modify one, we save them all in the new format. Looks like there is a problem using a profile with no primary address if you have not re-saved it in the new format. Looking into it now (and re-opening this until I find the issue).

**Comment by jasonmunro** [comment]
Ok, found the issue and pushed a fix. Phew!
