### ISSUE TITLE
unread item only displays messages in the inbox directory

### ISSUE THREAD

**Issue by ornais** [jasonmunro/cypht#156]
If you have many mail with subfolder, the "unread" item only displays messages from INBOX directory, it won't display unread messages from subfolders.
(thanks for the work you're doing).

**Comment by jasonmunro** [comment]
By default, only the INBOX is included in the "combined views" (unread, flagged, everything). But you can add any IMAP folder by navigating to it and using the icon in the upper right of the page (the circle with a checkmark) to include it in combined views.

**Comment by ornais** [comment]
great!! I'll try it tomorrow.
Thanks again.

**Comment by jasonmunro** [comment]
No problem :) thanks for checking out the project. I will leave this open in case you run into an issue with it.

**Comment by ornais** [comment]
Unfortunatly it is not working.
I have a unread email in a subfolder. This subfolder is added with the circle button. But the email doesn't appear in the combined view (UNREAD).

**Comment by jasonmunro** [comment]
In the upper right of a combined view there is a folder icon, it shows the sources included in the view. Does the subfolder show up in that list? Combined views have 2 limits on each source: A maximum number of messages from the source, and a time cutoff. Is the message date within the time cutoff?

**Comment by ornais** [comment]
It seems to work. Sorry for the inconvenience.

**Comment by jasonmunro** [comment]
No problem at all :)
