### ISSUE TITLE
Cannot MOVE email to another folder

### ISSUE THREAD

**Issue by neildarlow** [jasonmunro/cypht#158]
Running Cypht in following environment:
FreeBSD-10.3-RELEASE
nginx + PHP-5.6 (FPM)
Cyrus IMAPd 2.4.x and Postfix 3.1.x

I am able to COPY then DELETE an email but any attempt to MOVE an email results in a failure error message.

**Comment by jasonmunro** [comment]
Hello!
Thanks for the feedback. I recently (12 days ago) fixed a problem with moving messages, hopefully this will fix your issue: https://github.com/jasonmunro/cypht/commit/ded54fccd59baac36526ae62bec21ea384cb0f48

If not, let me know and we can dig into it deeper.

**Comment by neildarlow** [comment]
Hi Jason,

My install was taken from Github last evening. Not sure of the commit but the comment referred to an updated German translation one day prior.

Would that commit have your recent fix in? If so, then I think it may be a different problem.

Regards,
Neil Darlow

On 2 December 2016 23:35:58 GMT+00:00, Jason Munro <notifications@github.com> wrote:
>Hello!
>Thanks for the feedback. I recently (12 days ago) fixed a problem with
>moving messages, hopefully this will fix your issue:
>https://github.com/jasonmunro/cypht/commit/ded54fccd59baac36526ae62bec21ea384cb0f48
>
>If not, let me know and we can dig into it deeper.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jasonmunro/cypht/issues/158#issuecomment-264591566

-- 
Sent from my Sony Xperia™ phone with K-9 Mail.

**Comment by jasonmunro** [comment]
Sounds like it is a new problem. Are you moving a message from one IMAP server to another, or on the same server? I will try to reproduce it and let you know if I find anything. Thanks again.

**Comment by neildarlow** [comment]
Hi Jason,

It was a move on the same server.

I use Cyrus IMAPd with folders configured as sub-folders of INBOX.

The move was a Spam e-mail from INBOX to INBOX/Junk.

I use / as the sub-folder delimeter not . but I believe that is acceptable. I've never had any problems with other clients.

Regards,
Neil Darlow

On 3 December 2016 17:45:07 GMT+00:00, Jason Munro <notifications@github.com> wrote:
>Sounds like it is a new problem. Are you moving a message from one IMAP
>server to another, or on the same server? I will try to reproduce it
>and let you know if I find anything. Thanks again.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jasonmunro/cypht/issues/158#issuecomment-264653902

-- 
Sent from my Sony Xperia™ phone with K-9 Mail.

**Comment by jasonmunro** [comment]
It's likely not a problem on your end. I don't have a Cyrus setup, but I just did some moves without any issues so not sure what is wrong yet. Could you try doing the move in debug mode to see if anything pertinent is present in the PHP log?  Section six here: https://cypht.org/install.html explains how to enable debug mode. If that does not provide a clue I will post a gist with some additional debug info so we can see exactly what we are telling the IMAP server, and what it's responding with.

Thanks again for the feedback and helping to troubleshoot the issue.

**Comment by jasonmunro** [comment]
also, I like your avatar :)

**Comment by neildarlow** [comment]
OK. Enabled debug mode and Debug is shown on the action panel after logging in.

Attempted to move an e-mail from INBOX to INBOX/Junk and it failed as before but nothing logged to my PHP error log.

**Comment by conspacer** [comment]
I have mixed results with moving messages between folders on the same IMAP server. Sometimes it works, other times it times out. I am assuming issues in latency between the Cypht server and the IMAP mail server (but it does work at times).
Moving messages between servers (ala TBird style) times out 10 out of 10 times.

**Comment by jasonmunro** [comment]
The following will output the conversation(s) with imap servers when trying to move messages: https://gist.github.com/jasonmunro/efd8611bf7cc26ad0c788df5de5018ba

You need to be running in debug mode, and the output should show up in the PHP log file. Hopefully this will provide more insight into what is going wrong.

**Comment by neildarlow** [comment]
Hi Jason,

Attached is my nginx error log which contains the conversations you
might be after.

The content is a bit verbose but you can pick-out the packets of
interest I think.

Let me know if I can assist any further.

Regards,
Neil Darlow

**Comment by jasonmunro** [comment]
@neildarlow, not seeing any attachment. If you are worried about posting that online feel free to send it directly to me at jason@cypht.org. Thanks!

**Comment by jasonmunro** [comment]
@neildarlow thanks for sending the output, found the problem :) Your IMAP server does not support the MOVE extension (https://tools.ietf.org/html/rfc6851) and we don't have code to fallback to COPY/DELETE. Looking at adding support for that now.

**Comment by jasonmunro** [comment]
Fix is pushed. If the move extension is not supported, we fall back to copy/delete/expunge. I'm surprised this hasn't come up before. We want to take advantage of any extensions present, but we don't want to rely on them for basic functionality.

If you could pull the latest and see if it resolves your issue, that would be great. Thanks!

**Comment by jasonmunro** [comment]
@conspacer the OP issue is resolved, but that does not explain the errors you are seeing. Any chance you could try the debug I posted and send me the results? Thanks!
