### ISSUE TITLE
Canned Messages

### ISSUE THREAD

**Issue by VoIcanis** [jasonmunro/cypht#164]
This is a suggestion for an enhancement.

Having the ability to store and used html canned messages in outgoing emails.

Message name
Message body

And having it replace things in the message body like %RECIPIENTFIRSTNAME% with the recipients first name

**Comment by jasonmunro** [comment]
Thanks for the feedback!

**Comment by dumblob** [comment]
This seems to be a specific case of the general proposal on https://github.com/jasonmunro/cypht/issues/115 .

**Comment by ulfgebhardt** [comment]
This is an EMail Client, not a Massmailer.
This should not be a Standart-Feature.
If this is implemented it should be done as addon/plugin.

**Comment by dumblob** [comment]
>This is an EMail Client, not a Massmailer.

I believe it doesn't matter what it is at all. IMHO Cypht just tries to offer what people need for managing emails. And this approach is fine in my opinion.

>This should not be a Standart-Feature.

Why not? I don't see absolutely any reason for not having it as a standard feature.

>If this is implemented it should be done as addon/plugin.

Which is exactly what's proposed in the above-linked issue number https://github.com/jasonmunro/cypht/issues/115 .

**Comment by jasonmunro** [comment]
Everything in Cypht is a module set (plugin), so if this gets implemented it won't be in the core module set :) I'm pretty ambivalent about it really. I can see both sides of the issue. Personally I never use canned messages, but I can see how if one did, having that ability inside your client would be useful.
