### ISSUE TITLE
Question: How does auto-save currently works?

### ISSUE THREAD

**Issue by dumblob** [jasonmunro/cypht#166]
There was some planned work on auto save of composed messages, but I could not extract how does it work currently. Does it support only Gmail? Or is it implemented for any account? Does it use Drafts or Templates folders? How frequently is the email saved (I would prefer every 2 seconds)? How does it cope with encryption?

Thank you.

**Comment by jasonmunro** [comment]
Drafts are saved in the session every 30 seconds (or when you use the "save" button). When the session expires (logout, browser close) drafts are destroyed. Session data is encrypted with a unique key generated at login and stored in a cookie. Once a draft has been saved, you can access it after revisting the compose page with the document icon in the upper right of the page. Drafts are not tied directly to a particular mail provider. I have recently built support in the imap_folders module to set a draft folder, but it is not used by the draft system yet.

**Comment by dumblob** [comment]
Thank you @jasonmunro for explanation. For my needs, I would like to change the interval of autosaving to a much shorter value (e.g. 2 seconds). Autosave should trigger only if any change to the draft appeared (to save bandwidth). Could this autosave interval be configurable (either system-wide or even user-specific)? Or is it too low level and I should maintain my own fork?

**Comment by jasonmunro** [comment]
I'm not too keen on exposing this as a user option, I'm considering a site level ini file setting. In the meantime however, I don't want unneeded forking :) So, I'm leveraging the module system and the "site" module to make this possible without having to fork:

https://github.com/jasonmunro/cypht/blob/master/modules/site/site.js

All you have to do is enable that module, edit the site.js file above to your liking, and run your config gen script and you should be good to go. The point of the site module set is to override default Cypht behavior without making code changes, so this seems like a good place to put this for now.

I don't think the draft saving code is smart enough to not fire on each interval when nothing has changed in the draft, I'm looking into that now.

**Comment by jasonmunro** [comment]
Draft logic updated in https://github.com/jasonmunro/cypht/commit/012cc310a115140619d61f44127054fa1a107042 to only re-save if the draft has changed since the last save.

**Comment by dumblob** [comment]
Thanks a lot @jasonmunro! I'm closing this as solved.
