### ISSUE TITLE
Suggestion: click on IMAP servers' names brings up add/modify folders window

### ISSUE THREAD

**Issue by dunstn** [jasonmunro/cypht#168]
Could you please modify Cypht so that when one clicks on an imap server's name in the Email part of the menu, the /?page=folders&imap_server_id=xx page would come up? It would make folder configuration more simple, and there is no page yet that appears when one clicks on an imap server's name. 
Also, the Sent folder could be automatically selected if a folder called "SENT" (or "Sent", "sent") is present.  Until I found this setting, I hadn't know that it should be set to keep my outgoing mail, so I had assumed Cypht didn't work correctly.

**Comment by jasonmunro** [comment]
I like the idea of making the folder management page more accessible, but currently clicking on the imap server's name in the Email section of the menu expands the top level folders, so I would rather not change that link. The Sent and Trash folder settings are pretty new, so it's not so much that you missed them, it's that they did not exist until recently :)

Cypht supports auto-detecting special folders for IMAP servers that support that feature (for the Sent folder anyway). I would rather continue to use that and the manual setup than guess the folder name.

Maybe we could insert a "mange folders" entry into the top level of folders for the imap server with a different icon that takes you to the folder management page with that server selected?

Thanks for the feedback

**Comment by dumblob** [comment]
>Maybe we could insert a "mange folders" entry into the top level of folders for the imap server with a different icon that takes you to the folder management page with that server selected?

That might suffice.

**Comment by jasonmunro** [comment]
Just pushed this, if you guys could check it out and let me know what you think that would be great. Here is a screenshot:
![folder_manage](https://cloud.githubusercontent.com/assets/3793556/23471850/642bb194-fe70-11e6-81eb-7b5fa3df9594.png)
