### ISSUE TITLE
Inline messages body cropped

### ISSUE THREAD

**Issue by szilardx** [jasonmunro/cypht#175]
Thank you for this great work! I could finally settle with a mail solution :)

I got a display problem: the body of inline messages got cropped. 
Probable solution:
cypht/modules/inline_message/site.css 
`.search_content .msg_text, .message_list .msg_text { float: right; width: 50%; height: 50%; max-width: 50%; overflow: hidden; }`
height should be 100%, or not set.

Thanks!

**Comment by jasonmunro** [comment]
Interesting. I'm not seeing this behavior in chromium on linux, however I went ahead and removed the height rule from that css file in da8d9579 Let me know if that fixes the issue for you. Thanks for the feedback!

**Comment by szilardx** [comment]
Thanks, it solved it. I am using ubuntu-gnome, and chromium here also.
I investigated the problem, and it seems that the "height: 50%" was causing no problem, if the email was shorter then the email list on the left side. But I just got a super long email, and that revealed this problem.

I also found an other issue with inline messages: if the email is displayed in html, and has the width set, or the mail has a weirdly long attachment name, that cannot be wrapped, then you cannot see for example the download button, because the table has the overflow:hidden. So as a quick fix, that could be removed too.
I attached a screenshot showing the problem with attachments - overflow:hidden switched off for .msg_text in inspector.

I also have an another issue: downloading pdf, or xlsx attachments kind of works (hangs a little bit at 1mb) with Chromium, but fails completly in Firefox (ubuntu also), and on Android. I tried some settings already in nginx, and php-fpm, but no solution. Should I open an other issue here about this, or via email?

Thank you very much for the work!

**Comment by jasonmunro** [comment]
@szilardx Thanks for the follow up. I just removed the overflow property. As before, I'm not seeing this behavior, but I also don't see any reason not to remove it (not sure what I was thinking when I added it!).

If you could retest that would be great, and if it's resolved for you feel free to close this issue.

Could you please open a new issue for the download problem? It helps me keep track of things if we keep issues separated.

Thanks!

**Comment by szilardx** [comment]
Thanks, it works perfectly now!
