### ISSUE TITLE
can't see custom folders in gmail imap

### ISSUE THREAD

**Issue by mazhigali** [jasonmunro/cypht#179]
Hi, when i click on the *plus" nothings happens
![image](https://cloud.githubusercontent.com/assets/26579521/24248207/97e3de46-0fdf-11e7-9211-f094de08e413.png)
**but folders realy exist in gmail**
![image](https://cloud.githubusercontent.com/assets/26579521/24248371/276e8a98-0fe0-11e7-9009-e3f5b0d45dcf.png)

**Comment by jasonmunro** [comment]
Weird. What about the "[Gmail]" folder, does it expand properly? I have not run into this problem. I'm going to test a few things and see if I can reproduce the issue.

**Comment by jasonmunro** [comment]
I'm still unable to reproduce. I have a debug I want you to try if you can. Apply the following change:
https://gist.github.com/jasonmunro/0e0925d5c8035dd593d7d1611be2ad32
Then logout, back in, and expand the folder. You must be running  in "debug mode"  (as described in section 6 here https://cypht.org/install.html). You should then get the results of the IMAP command in the PHP error log which will hopefully provide a clue. Thanks!

**Comment by mazhigali** [comment]
after patch nothing happens in log, and i couldn't enable debug mode because of my low level in VDS, i use isp manager, sorry for bothering you, may be someone else has such problem and will help you

**Comment by jasonmunro** [comment]
It's no bother! I appreciate the feedback. I wish I could reproduce it so I can fix it :)

Just to clarify:

- When you click the plus on that folder, nothing happens, including no error message?
- Does the other expandable folder work (the [Gmail] one)?

Thanks

**Comment by mazhigali** [comment]
> When you click the plus on that folder, nothing happens, including no error message?
no error

> Does the other expandable folder work (the [Gmail] one)?
it doesn't work in yandex too

**Comment by dumblob** [comment]
@mazhigali is the problematic folder originally from Yandex whereas you're accessing it through the Gmail client capability (allowing Gmail logging into foreign email accounts like those on Yandex)? Do you have Cypht configured only for this Gmail account which itself is already a client for a Yandex account?

**Comment by mazhigali** [comment]
@dumblob Cypht connects straight to yandex and gmail accounts. 
These accounts have one common thing that they have 3 levels of subfolder nesting.

**Comment by jasonmunro** [comment]
@mazhigali Figured out how to reproduce this. It has to do with non-ascii characters in the parent folder name. Working on a fix!

**Comment by jasonmunro** [comment]
Fixed in https://github.com/jasonmunro/cypht/commit/5adde42d90642fec87809ce0d6ad720e3cacc956 @mazhigali if you could update and test that would be great. This change fixed the problem for me. Thanks!

**Comment by mazhigali** [comment]
@jasonmunro Thanks. now it's working
