### ISSUE TITLE
Attachments download fail or lag

### ISSUE THREAD

**Issue by szilardx** [jasonmunro/cypht#181]
I have one strange issue with Cypht:
Firefox cannot download attachments from imap (tested with gmail and outlook), Chromium can download, but the download lags, for example it stops at 1mb for a 1,5 mb pdf.

I have tested with nginx, tried multiple settings in the config.
Just tested with a standard apache install, it has the same problems. DevTools in Firefox shows that nothing gets actually transferred, and then it timeouts, and download fails.

Have you experienced this? Can you advice me about nginx config, or anything?

Thanks!

**Comment by jasonmunro** [comment]
I have not experienced this, but I will try to reproduce and let you know what I find!

**Comment by jasonmunro** [comment]
I can reproduce this with a 1.5 MB PDF and firefox, and I think I see the problem. We are sending the content-length header, but it's incorrectly reporting the size of the file. Chrome seems to handle this ok, but firefox simply fails. Removing the length header makes it work. I'm not sure I can predetermine the size of the file, so removing the header might be the only fix. If you want to test and see if that works for you, comment out line 383 of modules/imap/modules.php.

I will update this issue once I commit a fix.

**Comment by szilardx** [comment]
Commenting out the line fixed the issue quickly, and attachments are downloaded instantly.

Thank you very much! :+1:  :)

**Comment by jasonmunro** [comment]
Thanks for testing this out! Committed in https://github.com/jasonmunro/cypht/commit/9590feeff237fc10b5f78adc3505dcf25115a48d
