### ISSUE TITLE
attachents in inline message is too long

### ISSUE THREAD

**Issue by mazhigali** [jasonmunro/cypht#183]
HI. horizontal scroll is too big in inline message
![image](https://cloud.githubusercontent.com/assets/26579521/24660663/c5fafb84-1958-11e7-8c08-10f1a9084dc3.png)

**Comment by jasonmunro** [comment]
Looks like 2 bugs - the layout and the attachment filename is not decoded. I will look into it.

**Comment by jasonmunro** [comment]
Just pushed a fix for this in https://github.com/jasonmunro/cypht/commit/05aad356c43488cc2082997e2c9b95b3d6ee828d

This does the following:
- properly decodes the filename/descripiton field
- forces the message parts section to be the same width as the message
- hides the encoding and charset columns when using inline message view to save some horizontal space
- forces long names that would expand the table to overflow: hidden so they don't stretch the layout

This should help! Also, you can enable the "Show simple message part structure when reading a message" option in Settings -> Site which will save a bit more horizontal space by not showing the complete nested message structure and only display the downloadable attachments.

If you could test this out and let me know if it's better for you that would be great. Thanks for the feedback!
