### ISSUE TITLE
Adding POP3 Server Does nothing on production site

### ISSUE THREAD

**Issue by Ak-0** [jasonmunro/cypht#187]
The problem occurs when I try to add a POP server from servers tab.
It works easily when I do it from mail-debug setting.

**Comment by jasonmunro** [comment]
bug confirmed. Very strange, even my existing pop3 server is not showing up in prod (one I added from debug mode). I will update you once I figure out what the heck is going wrong here!

**Comment by jasonmunro** [comment]
This was a problem with the config gen script. Fixed in https://github.com/jasonmunro/cypht/commit/ab0bb67a3a2fbb4ccf13394c0dc5b4e3dee16d95
If you update and rerun the config_gen.php script it should resolve the issue.

**Comment by Ak-0** [comment]
Yeah, that fixed it, Great support here. Thank alot!
