### ISSUE TITLE
National character issues in email subject, and searching

### ISSUE THREAD

**Issue by szilardx** [jasonmunro/cypht#192]
I discovered a strange problem:
Whenever I use national characters in the e-mail subject, Cypht sends the mail subject with no spaces. So the words got concatenated.

For example if the subject is:
"árvíz tűrő tükör fúró gép", it becomes "árvíztűrőtükörfúrógép".
("árvíztűrőtükörfúrógép" is a hungarian font testing word, because it contains all our special national characters)
Also an another issue:
When I search for "árvíztűrőtükörfúrógép" it becomes "&aacute;rv&iacute;ztűrőt&uuml;k&ouml;rf&uacute;r&oacute;g&eacute;p" thus no search results.

Thank you for this great program anyway, I really enjoy using it every day!

**Comment by jasonmunro** [comment]
Thanks for the report. I will look into it and let you know!

**Comment by jasonmunro** [comment]
Just pushed 2 fixes, one for the subject formatting problem, and one for the search terms. If you could update and test them out that would be great!

Search term fix: https://github.com/jasonmunro/cypht/commit/736eed27abf610344840b13f7a73263156f8b491
Subject fix: https://github.com/jasonmunro/cypht/commit/7fa2e62d54e7d472a43cec3de7ed84a37555fe1d

**Comment by jasonmunro** [comment]
@szilardx I'm going to close this because I believe these issues are resolved. If you still have a problem related to these, please re-open. Thanks!

**Comment by szilardx** [comment]
Sorry for the late response, I just had the opportunity to test the fix. It works perfectly!

Thank you very much!
