### ISSUE TITLE
Normal functioning?

### ISSUE THREAD

**Issue by mwolfeu** [jasonmunro/cypht#195]
I have:
auth_type=dynamic
but accidentally left in:
; modules[]=dynamic_login

Regardless, I can type in a new user name/password in a browser and save it in a text file.  Is this intended?

**Comment by jasonmunro** [comment]
If you set the auth_type to dynamic, and you don't activate the module, it uses the "Auth type none" class (which really only exists for unit tests), that returns true for any username/password combination. This is a bug IMO. We should just "die" like we do for other misconfigured authentication configurations. Thanks for this feedback!

**Comment by jasonmunro** [comment]
Fixed in https://github.com/jasonmunro/cypht/commit/40ca661d436ded01c4731f13220cab13d95c5467 thanks again!
