### ISSUE TITLE
Left Side Bar Request

### ISSUE THREAD

**Issue by mwolfeu** [jasonmunro/cypht#197]
I have several accounts that I want to quickly scan every morning.  Viewing email inline is good but every time I click on a message the left side bar hides and I have to manually show it again.  Could it be an option to always pin it?

**Comment by jasonmunro** [comment]
The only reason I chose to hide it was to give a little more horizontal viewing space so the message list doesn't get so squished it's unreadable. It is a bit weird though, and maybe the default should be to not change it's visibility (that can be done independently anyway), and add an option to hide it on inline message view. I will update this issue once I deal with it! Thanks again for the feedback.

**Comment by jasonmunro** [comment]
Sorry it took so long to get to this. I disabled the auto-closing of the folder list. I also added a new inline message style. The default is the current layout to the right of the message list. The new style is inline in the message list itself. You can toggle the style in the General section of the Site settings page. If you run into any problems feel free to re-open this issue or create a new one. Thanks!
