### ISSUE TITLE
Add custom theme

### ISSUE THREAD

**Issue by hartois** [jasonmunro/cypht#199]
Hello,
how can I add new custom theme?
I think that it's is not a correct way to change hm_themes() function in modules/themes/modules.php

**Comment by jasonmunro** [comment]
I'm open to suggestions to make this easier. However I'm opposed to dynamically determining themes - they need to be white-listed somewhere. Right now to create a theme you create the css file in the modules/themes/assets directory, and update the hm_themes() function to include the filename and name used in the UI.

**Comment by hartois** [comment]
I see this as a configuration file with a list of themes

**Comment by jasonmunro** [comment]
Made some progress on this. You can now create a custom theme by doing the following:

- creating the css file and putting it in modules/themes/assets
- editing and moving the modules/themes/assets/themes.ini file (see the comments in this file for more info: https://github.com/jasonmunro/cypht/blob/master/modules/themes/themes.ini)
- rerunning the config_gen.php script.
