### ISSUE TITLE
"No valid recipients found." error with national characters in Compose

### ISSUE THREAD

**Issue by szilardx** [jasonmunro/cypht#201]
I guess something broke with the "national characters in the subject" fix - because now I get "No valid recipients found." error, if my recipient looks like this: "Ábc Déf" abcdef@example.com in the email sending - Compose view.

The problem is fixed if I remove the national characters - so it becomes "Abc Def".

Thanks for the great work!

**Comment by jasonmunro** [comment]
Should be fixed in the master branch. Thanks for the report!

**Comment by szilardx** [comment]
Tested it, thanks for the fix!
