### ISSUE TITLE
Can't post mails

### ISSUE THREAD

**Issue by mazhigali** [jasonmunro/cypht#202]
When i try to post a mail after clicking "send" button i have this error. What could be wrong? Month ago everithing was ok
![image](https://cloud.githubusercontent.com/assets/26579521/26755681/3bcaf668-489b-11e7-9a1c-5532b6dd4659.png)

**Comment by jasonmunro** [comment]
Odd, I can't reproduce this. I'm running the latest master branch, are you running the same or the 1.0.0. release?

**Comment by jasonmunro** [comment]
One possible cause could be the updates around profiles in the last few months. Can you make sure you are running the latest master branch, and also re-save one profile which should update them all to the new format (it should work with the older format as well, but just in case that is the issue). Thanks!
