### ISSUE TITLE
Help with oauth2 gmail - redirect URI?

### ISSUE THREAD

**Issue by szilardx** [jasonmunro/cypht#205]
I am trying to set up oauth2 autentication for one of my gmail accounts. I would like to try out the gmail contacts module.
I tried everything I could think of, now am a trying to do it from a freshly installed cypht instance.

I set a Google Gmail API Project - created the credentials. - although I am not sure what to put at the redirect URI field on the Google site - so I got confused what to put in the site_URI filed for the oauth2.ini
I tried it with my setup's address.

So far when I try to add a gmail account in cypht, nothing special happens - so I guess oauth2 is not working for me. Could you help me with this?
Thank you very much!

**Comment by jasonmunro** [comment]
The redirect URI in your Google app should be the URL of your cypht install, which should also be the value in your oauth2.ini file for client_uri. In order to use oauth2 over IMAP for Gmail and contacts, you need to use the "add E-mail" dialog from the nux module set. This should prompt you about using oauth2, then redirect you to Google to approve the oauth2 access, then redirect you back to your site with the newly added account (which should include IMAP, SMTP, and contacts).

**Comment by szilardx** [comment]
Thanks for the quick response.
The things I did:
- I created a new project in the Google API's manager. Enable Gmail API.
- Generated Oath Client ID.
- Copied the client ID, and client secret to the oauth2.ini, and filled in the client_uri filed. 
- Copied the oauth2.ini to /usr/local/share/cypht - next to the working hm3.ini.
- Regenerated the configuration. 
- I am trying the Add email - Gmail dialog, but it just prompts me for username, and password, as before, then successfully adds the email account - without oauth dialog.

**Comment by jasonmunro** [comment]
Maybe the oauth2.ini file location is the problem - it should be in the app_data_dir as defined in your hm3.ini file. Is that set to /usr/local/share/cypht?

**Comment by szilardx** [comment]
Thank you! I have gone through that setting option too, but was looking too hard for the mistake, so I missed it!
I used a bad directory. Thanks for the help, and this great application!

**Comment by Terramoto** [comment]
Hello,

I didn't want to raise another similar issue related to this, which might be probably just misconfiguration. I'm running the docker version, i've:

- setup the oauth2.ini file in app_data path specified in hm3.ini
- php script/config_gen.php

The file is detected during the config_gen.php, i then proceed to the interface, pick up the gmail option from the drop-down list. Setup the email address and name, proceed to the Google authentication, permissions page, check emails and calendars and then it redirects me to the webmail url but signed out. I type in login details but a "Error Ocurred" is displayed and the url reverts to the default webmail url  path.

I've notice the redirect URL sends two scopes:
?state=nux_authorization&code=(Authorization-Code)&scope=https://mail.google.com/%20https://www.googleapis.com/auth/contacts

I've tried removing the second scope and this time i got the "Error Ocurred" message but it didn't signed me off....
