### ISSUE TITLE
PHP Fatal error  Declaration of Hm_DB_Session::start must be compatible with Hm_PHP_Session::start on PHP 7.2

### ISSUE THREAD

**Issue by MurzNN** [jasonmunro/cypht#210]
I try to install Cypht on Ubuntu 16.04 AMD64 with PHP 7.2.0alpha3 and on step with running `./scripts/config_gen.php` I got the error:
```
PHP Fatal error:  Declaration of Hm_DB_Session::start($request) must be compatible with Hm_PHP_Session::start($request, $existing_session = false) in cypht/lib/session_db.php on line 173
```
PHP version is: PHP 7.2.0alpha3 (cli) (built: Jul  6 2017 11:55:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0alpha3, Copyright (c) 1999-2017, by Zend Technologies

If I try to downgrade PHP to 7.1 (7.1.7-1+ubuntu16.04.1+deb.sury.org+1) - all works well.

**Comment by jasonmunro** [comment]
Thanks for the report. I will get this fixed today. I also know that the libsodium integration is not correct for PHP 7.2 (it will fall back to OpenSSL). Hoping to get that fixed today as well.

**Comment by jasonmunro** [comment]
This and the libsodium issue should now be fixed in the master branch. If you can retest against PHP 7.2 that would be great. I would not be surprised to find other issues, but I don't have a PHP 7.2 env to test against here. Thanks again for the feedback.

**Comment by jasonmunro** [comment]
I have added PHP nightly builds to our Travis CI test runs and everything looks good so I'm going to close this issue. Please re-open or add a new one if you run into issues around PHP 7.2. Thanks!
