### ISSUE TITLE
Typo on main page in text mode

### ISSUE THREAD

**Issue by conspacer** [jasonmunro/cypht#211]
I was experimenting with Cypht in text mode (using Lynx) and was informed Javascript is required to use Cypht. I understand this, however I did find a typo. I am not sure where it is in the GUI version, but I am sure you can search the code for the typo.

Right above the login fields (though already logged in)..
`Unsaved changes will be lost! Re-neter your password...`

I didn't PrtSc on my headless machine, but I will remote in from a desktop and take a screenshot if you need it.

**Comment by Yamakasi** [comment]
@conspacer try to make a PR !

and join us on IRC > Freenode #hastymail

**Comment by jasonmunro** [comment]
@conspacer thanks for the feedback. This is fixed in the master branch
