### ISSUE TITLE
Login not possible with Cepht in iframe

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#213]
When Cepht is loaded into an iframe, even within the same domain like:

webmail.domain.tld <- cepht install
webmail.domain.tld/testdir/index.php <- iframe which loads the above install

The auth against the IMAP server goes well but you get an error like "The read operation failed" or something like the same on you IMAP server and you will be thrown back to the login page.

How to fix ?

**Comment by jasonmunro** [comment]
works fine for me, I just tested an iframe login locally and it worked without issue. Does your direct login without the iframe work?

**Comment by Yamakasi** [comment]
In a simple iframe it works but not like this:

My router (MVC) calls it like site.com/foobar(/maybe/more) where i load an iframe in a view to Cypht but there we have an issue, I also tried to use a subdomain to load it from, but we will have a cookie issue that we can set in Cepht, no solution.

My install of Cepht under the same domain is outside of my public dir...

**Comment by jasonmunro** [comment]
Not sure what to say about this. We know it works in an iframe, and it should not matter how that iframe is served (your router) - so something else is causing the problems you are seeing. can you explain in more detail the exact error conditions and log messages  you are seeing? Also, I know it's probably and autocorrect thing, but it's Cypht, not Cepht :)

**Comment by Yamakasi** [comment]
I will restest this again and report back... yes the typo, I'm ill and typing is painfull ;)

**Comment by Yamakasi** [comment]
This can be closed and is explained in the API login section.
