### ISSUE TITLE
Save settings without password auth

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#217]
It would be nice when we can save settings without the extra password Auth.

This auth is nice when you edit settings for external mailproviders like gmail and such but unneeded for local IMAP.

**Comment by dumblob** [comment]
> but unneeded for local IMAP.

I hope you mean just for the address `localhost`, but no other address (disregarding whether on the same LAN segment or whatever).

**Comment by jasonmunro** [comment]
@dumblob this request centers around a very specific case. We currently encrypt all user data stored between logins, as that could contain sensitive information. However, if you use IMAP authentication, and don't allow users to add additional E-mail accounts or profiles, no sensitive data will be stored outside the login session, meaning it would be possible to save the user settings without encrypting it, which would allow a user to save the data without re-entering their password. I'm not saying this is a good idea, but that is the background behind the request :)

**Comment by dumblob** [comment]
All right, this reasoning didn't appear to me. Then sorry for the fuss.

**Comment by Yamakasi** [comment]
I was thinking about that it might be nice that you can set in the config if people are able to select themself if they want to have multiple mailboxes, and if they can't it's IMAP only which will remove the password auth for storing.

How is this going so far ?

**Comment by jasonmunro** [comment]
Initial version is committed. here is the sample ini entry and description: https://github.com/jasonmunro/cypht/commit/d6bb8164ac480b088736006c58adfc9c0eed64bf

**Comment by jasonmunro** [comment]
I'm going to close this out since it's done - if you find any bugs please re-open a new issue. Thanks!
