### ISSUE TITLE
[Bug][Visual][Minor] When using Mail Icons, Move-to-Dialog is overlapped by Icons

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#220]
When using Mail Icons, Move-to-Dialog is overlapped by Icons

1. Set "Show icons in message lists" to true
2. Select a Message
3. Press move Button to Open Move Dialog

https://stackoverflow.com/questions/14045850/z-index-and-opacity-issues
The Problem is the Opacity of those Icons

Revision: [5f2d5c5f8e2f9083c84d795b8337ffc403eab42f](https://github.com/jasonmunro/cypht/commit/5f2d5c5f8e2f9083c84d795b8337ffc403eab42f)

![crypht6](https://user-images.githubusercontent.com/1238238/29709915-8b585ef8-898e-11e7-8d31-fcf30a2ba95d.png)

<3

**Comment by jasonmunro** [comment]
Just pushed a fix for this in 4ce06da3d. If you can confirm it fixes the problem for you that would be great. Thanks again for the feedback.

**Comment by ulfgebhardt** [comment]
fixed
