### ISSUE TITLE
[Bug] The sign Button on Compose has no effect

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#221]
When you have a Profile setup including a Signature the sign button has no visual Effect when composing

1. Make a Profile
2. Set a Signature on the Profile
3. Compose new Mail
4. Press "sign" Button
5. No Effect

Revision: [5f2d5c5f8e2f9083c84d795b8337ffc403eab42f](https://github.com/jasonmunro/cypht/commit/5f2d5c5f8e2f9083c84d795b8337ffc403eab42f)

<3

**Comment by jasonmunro** [comment]
Hello! I believe this is was fixed in 5400a3be6. Could you pull the latest and give it a try? Thanks for the feedback.

**Comment by ulfgebhardt** [comment]
I will give you some time to check out this #218 bug - since this is the only major bug i require fixing - then i will pull and confirm your fixes.

is that ok?

<3

**Comment by jasonmunro** [comment]
yep :)

**Comment by jasonmunro** [comment]
pushed a test fix for #218 in b9dd0e6

**Comment by ulfgebhardt** [comment]
fixed
