### ISSUE TITLE
[BUG][Display?] @mail.world.org behind every entity in To and CC Field

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#223]
When inspecting an EMail under "Sent" The "To" and "CC"-Field contain
> "Peter"@mail.world.org, peter@world.org
> &lt;"some@address.com"@mail.world.org>
> This seems to apply to Addresses in the local Address book

This might be an Serverproblem - i cannot tell yet. If you like I can make a seperate Issue for that.
> Looking at [is_email_address](https://github.com/jasonmunro/cypht/blob/master/modules/core/functions.php#L166) this could be caused by an "is-local-detection" false positiv

This is an Issue described in #218 and seperated from that thread

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
we don't use enable local addresses in the code, so I don't think that's the issue. Can you use the "raw" link  when viewing the message and show me what the actual header line for these address fields looks like? The "raw" view does not reformat the message at all except to make it safe to view in the browser. Thanks!

**Comment by ulfgebhardt** [comment]
Hey,
you are right - the Header contains the malformed Address already:

```
Return-Path: <peter@world.org>
Delivered-To: peter@world.org
Received: from world.org (world.org [123.456.789.123])
    by mail.world.org (Postfix) with ESMTPSA id ABCDEFG
    for <peter@world.org>; Mon, 15 Dec 2017 14:23:54 +0200 (CEST)
X-Mailer: Cypht
MIME-Version: 1.0
From: "Peter World" <peter@world.org>
Reply-To: peter@world.org
To: "Petra World"@mail.world.org, petra@world.org
Subject: Fwd: Re: Bla
Date: Mon, 19 Jan 2017 14:23:54 +0200
Message-Id: <123@world.org>
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: quoted-printable
X-Auto-Bcc: cypht
```
As you can see the To Field in the Header contains the malformed address.

`"Petra World"@mail.world.org, petra@world.org`

The reason for this is Postfix, which appends the @mail.world.org part on incomplete Addresses

> Transform an incomplete address into a complete address. For example, transform "username" into "username@example.com", or transform "username@hostname" into "username@hostname.example.com".
[source](http://www.postfix.org/ADDRESS_REWRITING_README.html)

Since this EMail was sent by Cypht I think it is still a Cypht-Problem, but on sending rather then on displaying an EMail. An incomplete Address is sent to the Mailserver, which appends the local domain to try making it a valid EMail-Address. Cypht should not send incomplete Recipients to the Server.

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Thanks for the update! I tested sending to the following:

"Jason Munro", <jason@cypht.org

it worked as expected. A message was sent to jason@cypht.org, and the first invalid address was ignored. The To: header of the E-mail was not changed in any way, unlike your results. Cypht parses the To/Cc/Bcc lines, pulls out all the addresses, and uses those in the SMTP conversation. Then it sets the To: address header to exactly what you entered - it does not append any domains or attempt to clean it up. 

So in this case Cypht did the "right" thing I think, except that it did no notify the user that the address line was malformed. I did not know about the php function to parse addresses, looks like that is a pecl package now. I'm not too keen on adding that as a requirement to run Cypht, but I will look into it. I would prefer to enhance our existing parsing path to notice malformed address lines and optionally notify the user if something does not look right.

**Comment by ulfgebhardt** [comment]
Ok - so I guess its a Postfix thingy... maybe mine is misconfigured or hacked :(

Could you try to send to
> "Jason Munro" jason@cypht.org
without the comma - that makes Problems aswell for me.

Grüße Ulf

<3

**Comment by ulfgebhardt** [comment]
Thanks for the Feedback. If you don't mind I would keep the Issue open for a bit longer, maybe i find the cause - if I don't I guess it should be closed. But its your call - if you can't reproduce the Problem, your obviously cant fix it.

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
I'm fine with keeping the issue open as long as you like. Just because I can't reproduce it does not mean there is not a bug in the code. Looks like Postfix earlier than 2.2 always does header rewrites, and after that it is something you can disable. I'm running a pretty default 3.1 postfix for cypht.org and I don't recall doing anything to disable header rewriting (but it's been a while since I set it up).

**Comment by ulfgebhardt** [comment]
Sorry for making you read all my stuff - Problem was Postfix

https://serverfault.com/questions/250855/postfix-disable-address-rewrite

`local_header_rewrite_clients =`

Solves this with Postfix 2.2

Grüße Ulf

<3

PS: Thanks for the great work, fast response time and all that effort you put into this awesome project!

**Comment by jasonmunro** [comment]
I'm always happy to help. Not only did you help me by finding some bugs that have since been corrected, but others coming here with similar problems can benefit from the resolution even if it was not a cypht specific issue. Thanks again!
