### ISSUE TITLE
Invalid characters in SMTP header

### ISSUE THREAD

**Issue by szilardx** [jasonmunro/cypht#224]
Sometimes when I reply to an email thread, and my company's email provider is in the loop, I get delayed and the failed email messages.
I have been able to drill down to the problem with the email admin. It seems like that Cypht sometimes leaves national (non ascii?) characters in the smtp header.
For example in some of my sent mail I found that the "cc:" field can contains national characters from my address book (or from the emails) like: éáűúőöüó
Other fields, like the to, and the subject has the code =?UTF-8? before them, and then some coded text(?), so I guess those work fine.

I can send real world example if that is need in private.
Thanks for the help!

**Comment by jasonmunro** [comment]
All non-ascii characters should be encoded before sending (with the?UTF-8? syntax you see in other fields), but we must be missing the CC field. I will look into it. Thanks for the feedback!

**Comment by jasonmunro** [comment]
Should be fixed in 3803a55a5 Thanks again!

**Comment by szilardx** [comment]
I tested it. No non ascii caracters with the test case.
Thanks for the quick fix! 👍
