### ISSUE TITLE
Cannot serve Cypht over custom port number

### ISSUE THREAD

**Issue by justinvoelker** [jasonmunro/cypht#226]
When trying to use Cypht over a custom port number (anything other than port 80), users are automatically and immediately singed out. I have traced the issue back to the validate_source() method within lib/module.php. There is an "if" statement that essentially compares source to target and when served over a custom port, the if statement ends up trying to compare the target of "192.168.1.101:8080" to the source of "192.168.1.101" which causes the problem. This difference causes the session to be destroyed.

**Comment by jasonmunro** [comment]
Thanks for the report. This is a bug and I will get it fixed ASAP.

**Comment by jasonmunro** [comment]
Should be fixed, if you could retest that would be great. Thanks!

**Comment by justinvoelker** [comment]
That appears to have fixed it as I can see the code is now getting past that point.

However, I am still just being redirected to the login page after authentication when I use a custom port so something else must be kicking me out. I will log another issue when I figure out what is causing that.

**Comment by jasonmunro** [comment]
@justinvoelker I had to make 2 changes to get this working, one in the origin check you pointed out, and the other when setting cookies, because the port number was incorrectly being included in the domain field in the cookie. Not sure if that is related to what you are seeing.
