### ISSUE TITLE
I search how to configure nginx

### ISSUE THREAD

**Issue by Mister6mik** [jasonmunro/cypht#229]
Hi all,
I search which conf to apply with **nginx** to run cypht on my **debian Jessie**
With a simple config (for a simple php project) don't work.

Sorry for my english.

A french boy!

**Comment by jasonmunro** [comment]
I don't have a Jessie system, but here is what I did on Debian Sid:

I already had nginx and apache2 installed, so I stopped apache, and did the following:
- edited the /etc/nginx/sites-enabled/default file to look like this:

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.php;
        server_name localhost;
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        }
}

```
- Ran "sudo apt-get install php-fpm" which also installed php7.0-fpm
- Started the php-fpm service, then nginx

That was it, Cypht worked when symlinked into /var/www/html/cypht and accessing it at http://localhost/cypht/

Hope that helps!

**Comment by Mister6mik** [comment]
Many thanks! 
I don't exactly use your code, but with nginx default config everything work.
