### ISSUE TITLE
Different source for Flagged folder

### ISSUE THREAD

**Issue by ovv** [jasonmunro/cypht#230]
Ideally (in my opinion) the Flagged folder should look in all directories. But that might not be possible so a way to set up the sources for this folder independently would be a nice to have.

**Comment by dumblob** [comment]
I'm curious - what does the "Flagged" folder do right now? I'm not using flagging, so I don't know how does it behave. I would though guess it's a filter for the "Everything" virtual folder in which case it would already look at all existing folders of all account in which we're currently logged in.

**Comment by jasonmunro** [comment]
The way things work now, is that all "combined views" (flagged, unread, everything) automatically include the INBOX from any IMAP account. You can add and remove folders from combined views by navigating to that folder in your IMAP account and use the controls in the upper right. We don't want to auto-include all folders for an account, as this could be excessive. You can see what is included in a combined view with the little folder icon in the upper right of the page.

The flagged combined view filters messages based on the IMAP "flag" state, a simple bool value. Either a message is flagged or not.

**Comment by ovv** [comment]
> The way things work now, is that all "combined views" (flagged, unread, everything) automatically include the INBOX from any IMAP account. You can add and remove folders from combined views by navigating to that folder in your IMAP account and use the controls in the upper right.

As I understand it if you add a folder to the combined views it's now present in the flagged, unread and everything. What I would like is to only include some folders for the flagged combined view.

I'll try to explain my workflow in detail maybe there is another way to do what I want. I try to follow the Zero Inbox so in each IMAP account I have two folders: 

1. Inbox
2. Archive

When an email come in, I either delete it, do something and once it's done move to archive or keep it in inbox if I want to deal with it later.

What would be awesome is to have a combined view of all my inbox in `Everything` (as it is now) and in the `Flagged` view show the flagged email in both the inbox and archive folder of each accounts.

I can understand this not being high priority but it would be a nice to have for my workflow. Even without Cypht is awesome !

**Comment by jasonmunro** [comment]
@ovv I understand what you mean. Technically there are 5 combined views:

- **Unread**: Contains "unread" items from any supported data source (IMAP, POP3, RSS, Github, etc), though you can exclude non E-mail related sources if you want like RSS feeds

- **Everything**: Every data source, no exclusions

- **Flagged**: IMAP specific combined views (IMAP is the only supported data source that supports flags)

- **Search**: Search applies to IMAP, POP3, and RSS data sources. Searches within IMAP accounts only search folders that have been added to the combined views (INBOX only by default)

- **Sent**: Another IMAP specific combined view that shows sent folders from all your IMAP accounts.

With that said, I think we should make some changes to make this more flexible and consistent across data sources. I think we should make it possible to add an IMAP folder to one of the five combined views but not the others as you suggest, and we should support that level of granularity across other data sources (right now either all RSS feeds show up on unread, or none of them. Would be cool to pick and chose a single feed for example).

I need to think about how I want this to work behind the scenes (and how to deal with the UI), but I appreciate the great idea and will let you know when I come up with something!

**Comment by jasonmunro** [comment]
@ovv I'm going to close this issue, and open a new one about adding the ability to specifically add one source (whatever it may be, RSS feed, specific IMAP folder, POP3 account, etc) to one combined view. I'm still unsure as to how I want to implement it, but I need a more targeted issue to remind me of exactly what the correct resolution should be. Thanks again for the feedback. Once I write up that issue I will reference it from this one and close this.

**Comment by jasonmunro** [comment]
See: https://github.com/jasonmunro/cypht/issues/283
