### ISSUE TITLE
🕷[Minor] HTML export of an EMail contains trailing Bracket Character

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#231]
HTML EMail-Export contain a ")" at the End when downloading the HTML Message and opening it in a Browser.

Raw EMail without Bracket:
![email_raw](https://user-images.githubusercontent.com/1238238/31955005-5ee264e4-b8e7-11e7-9a5e-6fa8d614454f.png)

Chrome Browser displaying the Bracket:
![email_html](https://user-images.githubusercontent.com/1238238/31955009-60ce0ca4-b8e7-11e7-99fe-ac4a039d8600.png)

Chrome Browser inspecting the Bracket:
![email_html_src](https://user-images.githubusercontent.com/1238238/31955092-9ed6a3e4-b8e7-11e7-8a6b-96a581d15487.png)

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Should be fixed, thanks for the feedback!

**Comment by ulfgebhardt** [comment]
✔ Confirming fix

Grüße Ulf

<3
