### ISSUE TITLE
Signature problem and Yahoo account sending problem

### ISSUE THREAD

**Issue by pvsgr** [jasonmunro/cypht#232]
Hello from Delphi, Greece,

I'm using Cypht for a month now and it's a really great program. I have just 2 issues with:
1) signature in sending emails does not work 
2) it's impossible to send (only send, reading is working fine) an email with a Yahoo account. Maybe it's a server related problem? (my Cypht install it's on a Vultr vps).

Wishing to contribute in this project, I have almost finish the greek translation. Please tell me how to send the file so you can add it in the Cypht package.

Thanks for this great software

**Comment by jasonmunro** [comment]
Hello!
Thanks for the feedback. I just tried sending with a Yahoo account, and while it was slow to get delivered compared to other SMTP servers, it did work (the message showed up in the recipient account about 5 minutes after sending). I used:

server: smtp.mail.yahoo.com
port: 465
tls: true

You can output the SMTP conversation to the PHP error log with the following code change:
https://gist.github.com/jasonmunro/7d9d3fbb8b695eaaef3ee492b9de5ba1
You must be running Cypht in debug mode for that to work however.

With regards to signatures, I fixed a bug that broke them a few months ago in the master branch, are you running the latest code? If not, can you try that and see if it's resolved? Note that you have to click "Sign" to add a signature to a message while composing it - it does not automatically add to the message when sending.

Thank you for creating a Greek translation! You can either create a pull request to get it added to the project, or you can just send it to me at jason@cypht.org and I will merge it.

Thanks again!

**Comment by jasonmunro** [comment]
Any feedback on these issues? Just checking in! :)

**Comment by pvsgr** [comment]
Hi Jason,

I was busy this days and forgot to send you a feedback.
The signature problem is resolved. The yahoo email sending aparently is a host problem!!!

Next week I will try to find out more about this host issue and I will keep you informed. I hope that the greek translation will be ready next week to.

Panos

Στις 30 Νοεμβρίου 2017 12:21:40 π.μ. EET, ο/η Jason Munro <notifications@github.com> έγραψε:
>Any feedback on these issues? Just checking in! :)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jasonmunro/cypht/issues/232#issuecomment-348016423

-- 
Σταλμένο από τη συσκευή μου Android με το K-9 Mail. Παρακαλώ συγχωρήστε την ολιγολογία μου.

**Comment by jasonmunro** [comment]
Thanks for the follow up. No rush, just wanted to make sure you were still there! :)

**Comment by jasonmunro** [comment]
As this has been out there for a while in the awaiting feedback state, I'm going to close it. @pvsgr if you want to re-open or have additional issues don't hesitate to let me know!
