### ISSUE TITLE
Gmail contacts fix with max-results and Issue with national characters

### ISSUE THREAD

**Issue by szilardx** [jasonmunro/cypht#237]
I finally had time to debug my gmail contacts issue.
I was missing some contacts, so I tested the Google Contacts API with Postman.
I was missing some contacts there too, so I found out that to retreive all contacts, you might have to use max-results parameter. https://stackoverflow.com/questions/23960122/google-contacts-api-not-getting-all-contacts

https://developers.google.com/google-apps/contacts/v3/#retrieving_all_contacts

I appended ?max-results=500 to
https://github.com/jasonmunro/cypht/blob/de5f5082dfeb27dad7a28278eef7f95c77c44e64/modules/gmail_contacts/modules.php#L83

And it works. I was able to get the missing contacts in Cypht.

I also realized, that some of my contacts name is broken due to national characters being present in their contact name. Sometimes the contact name is simply missing the part after the national character. Sorry for being this national character guy.

Thank you for your work! 👍

**Comment by jasonmunro** [comment]
I'm glad your the national character guy! I will check this out, thanks for the info

**Comment by jasonmunro** [comment]
@szilardx just pushed a test fix, and I added the max results of 500. Let me know if it's any better for you!

**Comment by szilardx** [comment]
@jasonmunro Thank you very much!
I have no missing contacts and all characters are okay! 👍

**Comment by jasonmunro** [comment]
Awesome!

**Comment by dumblob** [comment]
>...I added the max results of 500.

@jasonmunro is this a hard limit? Because I myself have over 1000 contacts and I'm certain I'm not alone. Is there a solution which does not constrain the number of contacts?

**Comment by jasonmunro** [comment]
@dumblob lets make this an option, I will file a new ticket for that
