### ISSUE TITLE
🕷Search in Mobile Version overlaps first few Results

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#243]
![crypth_search](https://user-images.githubusercontent.com/1238238/34501720-7cc2b2b0-f010-11e7-82e5-2731df5c4251.png)

In the Mobile Version the first Search Result is overlapped - depending on Device more or less. It always Results in the Inability to click the first Item

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
thanks for filing this, I knew about it, but kept forgetting to create an issue. Should be a pretty easy fix

**Comment by jasonmunro** [comment]
Should be fixed in https://github.com/jasonmunro/cypht/commit/ed4cd35c749b9e16a130a05d1da2fe05a76ba425

**Comment by ulfgebhardt** [comment]
Not fixed on my mobile

**Comment by dumblob** [comment]
> I dont think there is a need to see the Search Box at all times, its better to show more Results rather then the Searchbox.

I second this proposal with one minor change - namely the search box must be **available** all the time (e.g. through a menu), but **not shown** all the time.

**Comment by jasonmunro** [comment]
I agree a non-fixed search form is better, or one that can be hidden, but it turns out the non-fixed version is slightly trickier. For now I reduced the form field widths of the select boxes to keep it from wrapping which fixes the main issue for now.

**Comment by ulfgebhardt** [comment]
I will update the next few days and inform you about changes

Grüße Ulf

<3

**Comment by ulfgebhardt** [comment]
Fixed as in Rev 34d70a0240c10b6b8ab9fedf7c96cf8a0ef0ed53

Thanks! Great Work!

Grüße Ulf

<3
