### ISSUE TITLE
🕷 [Minor] EMails in<mail@world.org> Format cause Problems

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#246]
This is the Followup on #218 which i closed, since most of the Problems there were fixed.
The remaining Problems are listed here - think this makes it cleaner

Problem 1:
1. "peter@world.org" &lt;peter@world.org> in CC
2. reply all
3. "peter@world.org>" &lt;peter@world.org> in Compose CC (note the trailing >)

Problem 2:
1. Have Email in Sent with To-Field = &lt;peter@world.org>,&lt;petra@world.org>
2. Sent-List displays a comma in To-Column but no values: ","

Rev: 26a3870e58702787c0b8356863b8c4108a9bf1d7

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
I just recently refactored a lot of the address parsing related code. Could you update to the latest master to see if these issue persist? Thanks!

**Comment by ulfgebhardt** [comment]
I will soon and let you know, thanks! Your the Best!

Grüße Ulf

<3

**Comment by ulfgebhardt** [comment]
![sent](https://user-images.githubusercontent.com/1238238/34598526-8e4d1758-f1ed-11e7-9517-0b19bf14a13f.png)

Problem 2 remains

**Comment by ulfgebhardt** [comment]
The Sent-Folder shows now also the EMail, but the Quotations remain - and they are empty.

Therefore chaning Title to Minor

![sentproblem](https://user-images.githubusercontent.com/1238238/35194170-2781ee08-feaf-11e7-8323-378030c66ff3.png)


Rev: 34d70a0240c10b6b8ab9fedf7c96cf8a0ef0ed53

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Sorry, I forgot we still had an issue here - I will try to get this resolved this week.

**Comment by jasonmunro** [comment]
Using the new(er) address field formatting functions to clean up this field, the fix applies to all message lists not just sent. Looks better here, let me know if it does for you too!

**Comment by jasonmunro** [comment]
This should be resolved - if not please re-open!

**Comment by ulfgebhardt** [comment]
Confirming fix
