### ISSUE TITLE
✨ Support mailto links including subject, body, cc, bcc

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#251]
[Feature Request]

Please support the subject, body and other parameters, which are standard for mailto-links.

Here is a [Testpage](http://www.scottseverance.us/mailto.html) to demonstrate diferent parameters for mailto-links.

Some more Info about [compatibility](http://mc-computing.com/HTML_Examples/MailTo.htm).

Grüße Ulf

<3

**Comment by dumblob** [comment]
I believe this is a specific feature just for the html content type as discussed in https://github.com/jasonmunro/cypht/issues/12 .

**Comment by jasonmunro** [comment]
@dumblob I don't know why this would not apply to plain text messages as well. Should be relatively easy to code up support for this.

**Comment by dumblob** [comment]
@jasonmunro there are more reasons for that (basically the first one says it all, but for demonstration...):

1. mailto links are defined in the HTML standard (and probably in similar XML-like standards) and nowhere else - i.e. they are expected on certain places, but absolutely not on other places
2. plain text uses deliberately the word **plain** to show, that there is no distinction for the user between any two data chunks/files (disregarding what the content is - one can see e.g. an HTML document as plain text)
3. plain text has no semantics, but adding this feature would add some very specific semantics - in that case we should definitely rather use an additional "view type" like "smart text"
4. plain text has no syntax - why should the string `mailto:"clickable text hiding some address"<this.will@be.hidden>` or `mailto:some@address.com?subject=%C5%BD%C3%A1dost%20o%20partnerstv%C3%AD&body=V%C3%A1%C5%BEen%C3%AD%20z%20OpenAlt%20z.s.%2C%0A%0Ar%C3%A1di%20bychom%20se%20stali%20partnerem%20Va%C5%A1%C3%AD%20konference%20OpenAlt.%20Kontaktujte%20n%C3%A1s%20pros%C3%ADm%20prost%C5%99ednictv%C3%ADm%20n%C4%9Bkter%C3%A9ho%20z%20n%C3%A1sleduj%C3%ADc%C3%ADch%20kan%C3%A1l%C5%AF%3A%0A%0AEmail%3A%0Aatd.%0A%0AS%20pozdravem%2C%0A%0AJm%C3%A9no%0A` be treated differently than e.g. `mailfrom:test@test2.org`? It just doesn't make absolutely any sense.
5. why not to use a mailto-compatible standard (e.g. HTML) to be able to use it? Why would I want to mix some standards to produce another non-standard view/format (most probably just Cypht-specific)?
6. it's actually not so easy to code support for the full [mailto specification](https://tools.ietf.org/html/rfc2368 )
7. ... lots of other reasons (mainly derived from the above :wink:)

This rant is of course valid for addition of any specific meaning to chosen syntax constructs in plain text. Disregarding whether it's the mailto [URI scheme](https://en.wikipedia.org/wiki/Mailto ) or any other URI scheme or anything else.

**Comment by jasonmunro** [comment]
@dumblob i'm not suggesting we use mailto links in a plain text E-mail. Cypht supports starting a new E-mail from a mailto link - either in an HTML formatted message you are reading, or in another webpage if you allow Cypht to be your mailto link handler in your browser. The ask here is to support the other mailto fields and not just the To field. The only content type issue is what type of outbound message format you are using. If the body field in a mailto link supports markup, we will need to do a little conversion before we populate the compose page depending on what your outbound mail format is.

**Comment by dumblob** [comment]
Oh, then I'm sorry for the clutter - I misunderstood.

**Comment by jasonmunro** [comment]
Full mailto link support is pushed to the master branch. Thanks for the suggestion!

**Comment by ulfgebhardt** [comment]
<3 ur the best - just confirming that this works
