### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by bellinom** [jasonmunro/cypht#252]
Have you given any thought to packaging Cypht as a docker container? It could then easily be used on projects such as Cloudron.io or other selfhosting platforms.

**Comment by jasonmunro** [comment]
Hi @bellinom, thanks for the feedback. We actually have a docker config, the code is here:

https://github.com/jasonmunro/cypht-docker

And our docker hub page is here:

https://hub.docker.com/r/sailfrog/cypht-docker/

I don't use docker, so I actually have not tried it out. I know someone did recently and had some issues, but I don't know if it was cypht specific so I'm not sure of the state of things.

**Comment by bellinom** [comment]
Thanks, I missed those!
