### ISSUE TITLE
🕷 [Minor] [Visual] Move Dialog changes Foldernames to lowercase sometimes

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#254]
If you open the Move Dialog it tends to display Folders in lowercase, sometimes tho they have their right Names including case - its unpredictable how/when this is happening

### Stepps

1. Have Folder with Upper Case Characters
2. Use Move-Dialog and Navigate to the specific Folder
3. See it lower-/uppercase in the Move-Dialog, depending on ???
4. ...
5. Profit

### Move Dialog in Lowercase
![movelower](https://user-images.githubusercontent.com/1238238/35194328-644c45a6-feb2-11e7-851a-b137a72bc2c6.png)

### EMail Sidebar showing Uppercase (always correct)
![emailupper](https://user-images.githubusercontent.com/1238238/35194330-667c8764-feb2-11e7-8b94-f18f69c2319d.png)

### Other Info

This is a minor Bug, it only affects the Display of the Folders, not the Move Operation itself.

Rev: 34d70a0240c10b6b8ab9fedf7c96cf8a0ef0ed53

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
This is weird. We actually use javascript to clone the folder list to create the move/copy dialogs. I can't explain why this is happening and I can't reproduce it :/

**Comment by Yamakasi** [comment]
In which browser is this happening or does it happen on all of them ?

**Comment by ulfgebhardt** [comment]
I am using the latest Chrome(beta) on Desktop and an chrome including adblocker on Android mobile. Both Browsers show the same behavior.

I can try in TOR-browser(Firefox) and edge. I will give Feedback on my finds.

Can you tell me if it could be a server issue? Or is it pure Js executed in the browser?

Usual Steps(Desktop):
- Mark one or more Emails
- Move them with the Button in the top-bar
- See lowercase Folders in the Dialog popping up
- checking upon left side EMails Menu
- See correct Uppercase characters there

(Mobile)
- open Email
- click move button inside the EMail action-link-bar
- Dialog pops up with incorrect lowercase
- Select Folder and move the EMail
- press burgermenu to see and open the EMails Menu
- open Mailbox and see correct Uppercase characters there

Grüße Ulf

<3

**Comment by Yamakasi** [comment]
I will check the next couple of days. I have seen a duplicated folder list on some click/refresh in Firefox58.0.1 (64-bit) what @jasonmunro was not able to reproduce as well.

I think it's some JS caching issue which I need to recheck but as I'm now in singleserver config I don't see it (yet).

I will report back as well.

**Comment by ulfgebhardt** [comment]
This is not a browser-Issue, but an Inline-View Issue.

This happens when having an Inline-View Message open and click any Move button.

This issue also happens on mobile aswell, even tho it does not use Inline-View logic (maybe its config dependent?)

Browser able to reproduce:
- Chrome: Version 65.0.3325.51 (Offizieller Build) beta (64-Bit)
- Firefox: 57.0 (64-Bit)
- Firefox: 58.0.2 (64-Bit)
- Chrome on Mobile (Version: ???)

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
I think I know what it is. I think there is a text-transform css rule of "lowercase" accidentally being applied. I'm going to tag this with inline_message label and add it to the project to clean up that module set.

**Comment by Yamakasi** [comment]
What I have seen so far, and I cannot see yet if it's a browser issue, that if you click dropdown JS menu's twice without being dropped down yet, their content is duplicated in the same format under eachother.

So a double list is created for folder choice, as that is where it happens most I have seen.

**Comment by jasonmunro** [comment]
@ulfgebhardt Pushed a CSS change that fixes this here

**Comment by ulfgebhardt** [comment]
sry took me a while ;-)

confirming fix
