### ISSUE TITLE
Proper Draft support

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#257]
Currently we only manage drafts in memory. If you logout they are gone. Add support for a real IMAP draft folder to be used to save drafts while in progress.

**Comment by marclaporte** [comment]
Drafts are working and we are incrementally improving them
https://github.com/jasonmunro/cypht/pull/581
https://github.com/jasonmunro/cypht/pull/579
https://github.com/jasonmunro/cypht/pull/464
