### ISSUE TITLE
Split/Cleanup Session handler

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#260]
Hi,

Because I'm reviewing the sessionhandler for extending it for my own needs I also see that a lot of extending classes are used for several of backends that don't need eachother but only their functions.

As this is not ideal, is some split/cleanup to sesssion_base.php a willing cleanup ? I might be able to do this the next days.

Let me know.

**Comment by jasonmunro** [comment]
I'm not interested in doing this.

**Comment by Yamakasi** [comment]
That is why I ask, shall I create PR for it ?

**Comment by jasonmunro** [comment]
Please don't. I'm not interested in accepting changes to this code at this time.

**Comment by Yamakasi** [comment]
OK, if you say so.
