### ISSUE TITLE
Get config variables in site module

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#261]
What is the best way to get the config-variables in the site module ?

I guess it need to be something like this:

    private $config;
    private $name;

    /**
     * @param Hm_Config $config site config object
     */
    public function __construct($config) {
        $this->name = $config->get('parameter', false);
        $this->config = $config;
    }

**Comment by Yamakasi** [comment]
It's truely not in scope so I'm trying to find some reference in the code and found that way in the code when the config needs to be loaded.

Normally, or mostly, you simply do a $foo = new Class() you want but because of all the Extending/Inheriting this is a little bit confusing what the best and preferred way is.

**Comment by jasonmunro** [comment]
The config object is in scope inside the session class as $this->site_config, and from inside handler modules as $this->config. It is not possible to access it from a generic context. So if your class is extending the session or auth classes in the site module set, it's already present as $this->site_config.

**Comment by Yamakasi** [comment]
Yes fixed, it's already present indeed.

Thanks!
