### ISSUE TITLE
Site module Class(es) not seen

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#262]
I have a working Custom_Session class in the lib.php in the site folder which works on it's own domain with normal Cypth login.

When I move this (even copy the whole working version) to my own project and do an API login the Custom_Session class is not seen in the Session Type check and the SessionHandler defaults back to the PHP Session type. Memcached and DB work fine but it fails on class_exists() it seems:

https://github.com/jasonmunro/cypht/blob/master/lib/session_base.php#L403

I get the following error in my log:

> Got error 'PHP message: PHP Warning:  session_set_cookie_params(): Cannot change session cookie parameters when session is active in /home/dev/myproject/library/cypht/lib/session_php.php on line 226\nPHP message: PHP Notice:  session_start(): A session had already been started - ignoring in /home/dev/myproject/library/cypht/lib/framework.php on line 104\n', referer: http://myproject/login

I'm not able to debug why the class is not seen, maybe the site module is not included right because of the path where it lives in ? The production index.php settings are right.

**Comment by jasonmunro** [comment]
I don't know. Are you sure your setup has the custom session class set in the hm3.ini, and that you ran coinfig_gen after making changes? Are the files you moved in the correct place with the correct permissions? the site module set session override is loaded from the dispatch class here:
https://github.com/jasonmunro/cypht/blob/master/lib/dispatch.php#L190

**Comment by Yamakasi** [comment]
[ ] session_type=custom
[ ] modules[]=site
[ ] re-ran config_gen (multiple times)
[ ] rights are default OK, this has todo with some share that remaps the owner of the files on my dev system (same for my whole repo)

It seems it does not even load that __cunstructor and I think it has something todo with the API login as whatever I log in the Hm_Dispatch using error_log() this never get's logged when setting a cookie/session using the API.

I think there is the bug, the API does not dispatch because after the login failed and I visit the page in my app that gives the login path I see the dispatch error_logs. This happens on whatever session_type I use. 

I cannot remember if anything changed there as I'm just testing now again as I'm finishing up things, could be about 2+ months ago as I disabled it in dev to login using the API.

**Comment by jasonmunro** [comment]
try this:
https://gist.github.com/jasonmunro/a945c4e95d0277ba1e8548525424e833

**Comment by Yamakasi** [comment]
Yes, good idea that fixes the API/site part, but we need to move this more into the core so it never fails, so that was why I was digging there as I was not aware the app was not fully dispatched. As you want to keep that as minimalist as possible this is good for temporary fix in my case, but others will have the same with other backends but for the API we don't want to dispatch the full app I think.

Some other issue I now stumble in after a good session write is:

disable_ini_settings=false

`PHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/dev/myproject/library/cypht/lib/ini_set.php on line 27\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/dev/myproject/library/cypht/lib/ini_set.php on line 31\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/dev/myproject/library/cypht/lib/ini_set.php on line 34\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/dev/myproject/library/cypht/lib/ini_set.php on line 37\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/dev/myproject/library/cypht/lib/ini_set.php on line 48\n', referer: http://myproject/login
`

When I try to debug this with this

`disable_ini_settings=false
`

I get: 

`[9] => LOGGED IN
[10] => HTTP header fingerprint check failed
[11] => Deleting cookie: name: hm_session, lifetime: 1518210487
`

And when I want to debug that I get:

`[9] => LOGGED IN
[10] => IDLETIMER: timer exceeded, logged out
[11] => Deleting cookie: name: hm_session, lifetime: 1518210563`

Which logs me out directly.

I think this is because the rest is not dispatched as well, the modules.

**Comment by jasonmunro** [comment]
>  but we need to move this more into the core so it never fails

Moving code into the core does not mean it won't fail. It might make sense to abstract some things from the dispatch class to make them more usable. A base class with the methods required to support api based logins more directly, with the dispatch specific aspects moved to a class that inherits it.

I will have to think about it more.

You definitely need `disable_ini_settings=true` for your setup. IIRC, I created that option specifically for your integration.

The idle_timer module set is not compatible with the api login method when using the direct PHP login function from what I remember. To simplify troubleshooting I would disable that module set for now.

The header fingerprint check error should be fixed by setting the `disable_fingerprint=true` setting in your hm3.ini file. This was also created specifically for the PHP api login method.

**Comment by Yamakasi** [comment]
> Moving code into the core does not mean it won't fail. It might make sense to abstract some things from the dispatch class to make them more usable. A base class with the methods required to support api based logins more directly, with the dispatch specific aspects moved to a class that inherits it.

If implemented right it will not fail, that is why I suggested earlier to move the global session function to some abstract class instead of extending/overwriting the functions. This saves duplicate functions and create much more easy maintainable single functions which are "smarter".

> You definitely need disable_ini_settings=true for your setup. IIRC, I created that option specifically for your integration.

This came more to mind because of the idea when I was investigating multiple (lightweight) webmail clients and found out that most are able to be integrated and are an success because of that. It makes it more flexible in usage and implementation so everyone can have a benefit of it. I'm just the testcase to see where it could fail as Cypht was not designed for that as you stated.

> The idle_timer module set is not compatible with the api login method when using the direct PHP login function from what I remember. To simplify troubleshooting I would disable that module set for now.

This could be indeed best managed by the platform where it's integrated. You can simply create a JS listener and do a logout using the API from your own app. So maybe we just need to add some comments for "integration".

> The header fingerprint check error should be fixed by setting the disable_fingerprint=true setting in your hm3.ini file. This was also created specifically for the PHP api login method.

Overall this was a security feature you want. As far as you told me, Cypht was designed so you have your own webmail with all your own mailservices you have in one tool, but what if you place this behind a loadbalancer or everyone is accessing it from behind one IP, session hijacking is MUCH easier then, so it was a security concern in general as well discussed before. My concern was only, I place it behind a loadbalancer and what if the client IP is not seen as it's proxy-ed ? Even then, the idea was for Cypht as single user solution for multiple mailservices in general as understood on IRC. 

Future changes things which is good!

So far, this is solved. I will try to add some useful comments to the settings for integration and review the singleserver mode further for finetuning several of pages.
