### ISSUE TITLE
Session not removed from storage on logout when using API

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#263]
When you logout using the API the session is not removed from the session storage backend.

We need to call:

```
$session->destroy();
```
from the set sessionhandler

https://github.com/jasonmunro/cypht/blob/master/modules/api_login/api.php#L48

The issue that raises here is that $this->session_key is empty when using the API on logout. So we need to grab it from the still existing cookie again ?

We can let the $session->delete_cookie() on

https://github.com/jasonmunro/cypht/blob/master/modules/api_login/api.php#L51-L52

still exist to make sure the cookie is removed but let this also be managed by the destroy() functions in the session backends.

Better be safe then sorry and check if the cookie still exist before fire ?:

https://github.com/jasonmunro/cypht/blob/master/modules/api_login/api.php#L51-L52

**Comment by jasonmunro** [comment]
I will check it out, my initial thought is that it's a bug/oversight of the api login module set. thanks for the feedback.

**Comment by jasonmunro** [comment]
I don't have a way to test this right now, but this change should fix this:
https://github.com/jasonmunro/cypht/commit/ae259d77da082f02fcbc0bfbdcd9addce8a19711

**Comment by Yamakasi** [comment]
Yes good idea but this still gives an empty $this->session_key in the destroy function as far as I can see.

**Comment by Yamakasi** [comment]
Any update on this ?

**Comment by jasonmunro** [comment]
sorry, not yet. I will check ti out!

**Comment by Yamakasi** [comment]
Do you need to have some extra investigation about this or do you need to go deeper into your code for this ?

**Comment by jasonmunro** [comment]
Sorry, just super busy with work. I promise this is at the top of my Cypht todo list!

**Comment by jasonmunro** [comment]
@Yamakasi Just pushed a fix that works here - please pull the latest git and let me know!

**Comment by Yamakasi** [comment]
Thanks! I will test it out tomorrow (today actualy) I was busy as well so no worries! Thanks, let you know!

**Comment by jasonmunro** [comment]
I believe this is fixed so I'm closing this issue. @Yamakasi if it's not fixed for you when you get to test it out, please re-open this.
