### ISSUE TITLE
🕷Text-Mail Links take closing bracket ] into link 

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#264]
![image](https://user-images.githubusercontent.com/1238238/36351420-c47dc514-14a9-11e8-83b6-49a2a7ca8d7f.png)

Text EMails with [Brackets] enclosing links cause the href of the generated a-tag to include the closing bracket.

Reference: https://stackoverflow.com/a/13227416/1326872

Rev: 4e16293ba8f05c6ed6ac94d32ebd48980a7a4b40

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
square brackets in urls should be encoded, not sure why we were letting these through. Likely it's the "clients should be strict in what they produce, and forgiving in what the except" rule :). I have removed them from the allowed characters in the regex match, so this should be resolved.

**Comment by jasonmunro** [comment]
This should be fixed, so I'm closing. Please re-open if you find otherwise!
