### ISSUE TITLE
Settings saved with empty username in SingleServer mode

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#265]
When you enable SingleServer mode the account settings are saved but the username is empty so they are not able to be queried when you login again.

I need to investigate where this goes wrong, maybe you have a direct idea.

**Comment by jasonmunro** [comment]
I think this will fix it: https://github.com/jasonmunro/cypht/commit/6980166b426b686e13fd5a40d64c7616af56c8e8

**Comment by Yamakasi** [comment]
Yes this fixes it! Thanks.

**Comment by jasonmunro** [comment]
Thanks for the follow up
