### ISSUE TITLE
Cypht Integration with CodeIgniter

### ISSUE THREAD

**Issue by lysaan** [jasonmunro/cypht#266]
We are integrating Cypht into our application built using PHP Framework CodeIgniter. As CodeIgniter has its own Structure and Cypht has a different Structure. If Cypht.Org has any docs or samples for Integrating it with CodeIgniter then it will be very helpful.

**Comment by Yamakasi** [comment]
You can use the API but there is nothing more left then that.

If you want a CI based webmail you need to develop one yourself.

**Comment by marclaporte** [comment]
@lysaan: I work on [ClearOS](https://wikisuite.org/ClearOS), which uses CodeIgniter. And I am getting familiar with Cypht. So, I am very interested: How did your project go?

**Comment by lysaan** [comment]
> @lysaan: I work on [ClearOS](https://wikisuite.org/ClearOS), which uses CodeIgniter. And I am getting familiar with Cypht. So, I am very interested: How did your project go?

Well We have successfully Integrated Cypht into CodeIgniter based System. We are happy that we found couple of Bugs in Cypht and Got fixed by Cypht Team. How Cypht is working fine in the system.

**Comment by ulfgebhardt** [comment]
Will you share your code with us @lysaan ? <3

**Comment by jasonmunro** [comment]
@lysaan if you have integration code that you can share, I will happily create a repo for it and give you credit, or if you prefer create a wiki page linking to your own repo. If that is not something you can do I totally understand. Glad to hear you got it working!

**Comment by marclaporte** [comment]
@lysaan: any news?

Thanks!

**Comment by lysaan** [comment]
Hi guys, I was busy so my apologies for the delay. 
@marclaporte I think the easiest way to integrate Cypht to CI is to use Functional Login and Use Cypht in your System as iFrame.
1. You can put your Cypht code in CI 3rd Party OR Libraries directory and could use Functional Login for Authentication.
Ref: https://github.com/jasonmunro/cypht/wiki/API-Login

2. Configure hm3.ini file and Use Database for Authentication, Sessions and User setting
Ref: https://github.com/jasonmunro/cypht/blob/master/INSTALL

3. You can use iFrame after successful Login to You System and Cypht Authentication to use Cypht.

**Comment by marclaporte** [comment]
Ok, then, so closing this. Anyone searching the right keywords will end up here.
