### ISSUE TITLE
Webdav integration

### ISSUE THREAD

**Issue by Astaoth** [jasonmunro/cypht#268]
Hello !
I saw that there is ldap support, but it doesn't seem there is any carddav support. Do you think it is a feature which could be added to Cypht ?
There is also a calendar in Cypht, so could it be possible to add caldav support ?

Cheers !

**Comment by Yamakasi** [comment]
There has been asked before and is actually not that difficult itself to add (I think) but needs time.

I agree that it's far from ideal to have calendars without caldav as they live on their own, carddav the same actually these days.

**Comment by jasonmunro** [comment]
Both would be great to support, just need to find the time to code it up :) This is a duplicate request of this:
https://github.com/jasonmunro/cypht/issues/120
So I'm going to close this one. Thanks for the feedback!

**Comment by omocinteractive** [comment]
A WebDAV support would be nice for attachments to get files from cloud systems like owncloud/nextcloud. For online-workers like me a must have feature ;)
