### ISSUE TITLE
Display HTML

### ISSUE THREAD

**Issue by bet0x** [jasonmunro/cypht#269]
How i do display HTML before text while reading an email?

Thank you.

**Comment by jasonmunro** [comment]
Hello!

Navigate to Settings -> Site -> General
and un-check the box for: "Prefer text over HTML when reading messages" and you should be good to go!

**Comment by bet0x** [comment]
For some reason, remove images on the email are not getting loaded.. i have that unchecked

**Comment by rosoft2001** [comment]
Same issue

**Comment by jasonmunro** [comment]
By default Cypht will not load any external resource in an HTML formatted message - this includes images. Doing so is a huge privacy and security risk. The only way we can support this properly IMO is to allow a per-message override to reload the HTML with external resources, and eventually a white-listed list of senders that a user allows this behavior by default for. We cannot allow this for all senders as the risk is just to great.

**Comment by bet0x** [comment]
But... this can be optional right?

**Comment by dumblob** [comment]
@bet0x please see https://en.wikipedia.org/wiki/EFAIL (https://efail.de/ ) before you'll decide to reference any external content (which forces the recipient to make an online request with the deciphered URL).

**Comment by jasonmunro** [comment]
@bet0x to clarify, yes, this can be done (some of the behind the scenes work to allow it already exists), however, it would be insecure to add a "always allow external resources" option, so instead I am planning to add a link to the message view page that allows you to reload that specific message with external resources included.

**Comment by jasonmunro** [comment]
@bet0x Just pushed support for this. You need to add an option to your site ini to enable the ability to see external images (this disables the image content security policy header). When viewing an HTML message part with images, there will be an "Allow Images" link in the upper right side of the message content that will reload the message with images enabled.

Here is the new ini setting and explanation:

https://github.com/jasonmunro/cypht/commit/1b6e0959ca5f6dad074e0f726c0bb54ed757b3d8

**Comment by marclaporte** [comment]
@jasonmunro wrote "and eventually a white-listed list of senders that a user allows this behavior by default for."

Could this be abused? (email spoofing)

**Comment by jasonmunro** [comment]
@marclaporte probably, however you would have to know the user's white list in order to abuse it.
