### ISSUE TITLE
🕷 [Inline View] Inline-View Scrolls on long Titles

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#274]
![image](https://user-images.githubusercontent.com/1238238/40300498-ab823d64-5ce9-11e8-9fd0-7797ba1b4b02.png)

The Inline-View now scrolls on long titles after your Inline-View Update.

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
fix pushed to the subject css rules. Let me know if it looks better for you!

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/42724573-20c5c43c-8775-11e8-8a0e-dd94c75b9ce4.png)

It works better now.

![image](https://user-images.githubusercontent.com/1238238/42724582-4c3750cc-8775-11e8-81f4-58ce45cd6b0a.png)

But there is still a diference between the max. List size and the Inline-EMail Field as shown in Screeny2

Feel free to close this - this is behaviour is not a Problem in my normal Usage, but is rather forced by making the window size smaller.

<3

Grüße Ulf
