### ISSUE TITLE
🕷 [Minor] [CSS] Last line in previous Mail-Text is of the wrong color

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#275]
![image](https://user-images.githubusercontent.com/1238238/42410972-ae4123ec-81f3-11e8-81eb-800b281abd1f.png)

I guess the Screeny is self explanatory

**Steps to reproduce**
1. Reply to EMail
2. Type your Text and Send
3. Find Discoloration in Sent Folder
4. ...
5. Profit!

Grüße Ulf

<3

**Comment by jasonmunro** [comment]
Should be fixed @ulfgebhardt . Thanks for the feedback!

**Comment by ulfgebhardt** [comment]
Confirming fix <3 ty.
