### ISSUE TITLE
Add READMEs for individual plugins

### ISSUE THREAD

**Issue by beta-phenylethylamine** [jasonmunro/cypht#276]
As far as I can tell, all there is about each individual module is the short blurbs at https://cypht.org/modules.html, which is a pretty limited amount of information. Github has the ability to display READMEs at the bottom of the page in subdirectories so it would be useful to get a slightly more in-depth overview for each of them so that when you click the link on cypht.org you don't just get a few php files and actually get a bit more information

**Comment by jasonmunro** [comment]
Great idea. I will see what I can do!

**Comment by jasonmunro** [comment]
Added in commit https://github.com/jasonmunro/cypht/commit/9c7dc63f0667681899a011d57319c11a9afbacf3 thanks for the feedback!
