### ISSUE TITLE
IMAP Authentication Failure

### ISSUE THREAD

**Issue by ghost** [jasonmunro/cypht#282]
Stock install, set IMAP as the authentication mechanism. No information in the debug of cypht, however did catch these in mail.log:
` resist dovecot: imap-login: Disconnected: Too many invalid commands (no auth attempts in 0 secs): user=<>, rip=X.X.X.X[my_ip], lip=X.X.X.X[my_ip], secured, session=<t9Ntp4t28tQtPtOq>`

Every time I try and login using a system user and mail account for IMAP, it produces this. Almost as if it's not sending the proper commands.

**Comment by jasonmunro** [comment]
Can you try again with Cypht in debug mode? It will send failed authentication details to the PHP log that will likely provide a clue. Info on debug mode is here:

https://github.com/jasonmunro/cypht/wiki/Troubleshooting-Login-Issues

Also if you are running the latest release code, it's pretty old - I would recommend running the latest git checkout (need to get around to another release!).

Thanks for the feedback.

**Comment by jasonmunro** [comment]
Without additional feedback I can't address this issue. Obviously IMAP authentication is working for me :) If you still are having problems please re-open this issue or file a new one. Thanks!
