### ISSUE TITLE
bad url on site

### ISSUE THREAD

**Issue by lesar** [jasonmunro/cypht#289]
Hallo Jason on installation [page](https://cypht.org/install.html) there is a old link to be change:  
https://github.com/jasonmunro/cypht/blob/master/modules/contacts/ldap.ini  
I think that have to be:  
https://github.com/jasonmunro/cypht/blob/master/modules/ldap_contacts/ldap.ini

**Comment by jasonmunro** [comment]
@lesar you are correct, thanks for the feedback. Link is fixed and the website is updated.
