### ISSUE TITLE
Ldap contact and password strange behavior

### ISSUE THREAD

**Issue by lesar** [jasonmunro/cypht#292]
I'm trying cypht and I like it a lott.  

I have configured ldap module and work well. I have put user and psw in site config and not in the module ini file. I try to remove the user and psw but:  
* If I put a blank empty value no change are saved.
* If I put some random letter and save change, the change are saved, but the ldap contact module still read all contact.  

Is there a ldap search on the roadmap? 

Best regards,
Leonardo

**Comment by jasonmunro** [comment]
> I'm trying cypht and I like it a lott.

Thanks! I appreciate your feedback.

> I have configured ldap module and work well. I have put user and psw in site config and not in the module ini file. I try to remove the user and psw but:

I would not recommend doing that, but I don't think it breaks anything.

> * If I put a blank empty value no change are saved.
> * If I put some random letter and save change, the change are saved, but the ldap contact module still read all contact.

To clarify -  you are changing the hm3.ini file to remove the user and pass values for the LDAP server, then rerunning the config_gen.php script (and logging out and back in) - and it still is able to access the LDAP contact list?

If that is correct, are you sure your LDAP server is configured to require authentication?
 
> Is there a ldap search on the roadmap?

Not currently, but it would be a nice improvement especially for large addressbooks. I will create a new issue to track that request.

**Comment by lesar** [comment]
>To clarify - you are changing the hm3.ini file to remove the user and pass values for the LDAP server, then rerunning the config_gen.php script (and logging out and back in) - and it still is able to access the LDAP contact list?  

No I'm try to change this setting on http://localhost/mail/?page=settings  
under `Addressbooks -> Personal`  

In my hm3.ini I have put only the `ldap_auth_base_dn` and give the user and pws run time during authentication.

In ldap.ini I have ***not*** put user and pws.  
 
>If that is correct, are you sure your LDAP server is configured to require authentication?  

My Ldap server is configure to require authentication: I have installed it.  

Best regards,
Leonardo

**Comment by jasonmunro** [comment]
@lesar Ok, thanks for the clarification. I will dig into that part of the code and see what is going on!

**Comment by jasonmunro** [comment]
Looks like the code is not actually using the username and password from the settings page!  Because of that, we are doing an "anonymous bind" to the server. I just tested this locally and see what you are seeing.  However, if you are still getting a contact list from your LDAP server that likely means you have not disabled anonymous binding, so you might want to check that. I had to apply an ldif like:

```
dn: olcDatabase={-1}frontend,cn=config
add: olcRequires
olcRequires: authc
```

Working on a fix for the username and password now.

**Comment by jasonmunro** [comment]
A fix has been pushed to the master branch. Thanks for the feedback!

**Comment by lesar** [comment]
Thank you for the fix. You are right I have anonymous binding enable: I do not know that in ubuntu is enable by default.  

Now I have disable it.  

To disable it I have use this ldif:  
```ldif
#sudo ldapadd -Y EXTERNAL -H ldapi:/// -f /usr/share/slapd/ldap_disable_bind_anon.ldif
dn: cn=config
changetype: modify
add: olcDisallows
olcDisallows: bind_anon

dn: cn=config
changetype: modify
add: olcRequires
olcRequires: authc

dn: olcDatabase={-1}frontend,cn=config
changetype: modify
add: olcRequires
olcRequires: authc
```

**Comment by jasonmunro** [comment]
I believe this is resolved so I'm closing this issue. Thanks for the feedback! If you are still having problems please re-open or file a new issue.
