### ISSUE TITLE
🕷 Moving EMails fails silently

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#296]
Moving EMails often fails silently.

Steps:
- Navigate to an Inbox (I think it also takes place in "Everything")
- Select several EMails, open some to read before selecting them
- Use the Move-Button on top and select some Subfolder where to move them
- 50% of all cases the moving fails and only the first selected EMail is moved (if any)

Remarks:
- I use Inline-View
- I do this in a Folder not in the Everything-View, but i think it also happens in Everyhting
- This is very very annoying </3
- The "Popup" on top states "Messages moved" even tho it does not
- All EMails are unselected after the move Operation
- It might has to do with an Update taking place in the Background ( loading bar on top)

This did not happen before:
- Current 87b5c99b1238d49b6bc3ed8b94d3cd4327ec76a1
- Before 020f9b2cf74683b8967ec1a5cbe4dbd3fab851ba

**Comment by jasonmunro** [comment]
almost certain this is related to the recent work on moving the open message in inline view. I will check it out.

**Comment by jasonmunro** [comment]
I found the problem - context. The move/copy logic had no indication of which move/copy button was used, so the logic to collect the message ids was incorrect. I have added a context to the chain of function calls so when the move/copy is executed the code knows (message or list) and collects the correct message id(s). If you could test out the latest master branch and let me know if its resolved for you that would be great!

**Comment by ulfgebhardt** [comment]
Confirming fix,

your the Best!

Grüße Ulf <3
