### ISSUE TITLE
PHP Catchable fatal error:  Object of class Hm_Site_Config_File could not be converted to string

### ISSUE THREAD

**Issue by mpaolo** [jasonmunro/cypht#301]
## 🐛 Bugreport
Hi,
sent an email, did not see it in 'sent' folder. Then browser imap folders, tried to create a 'sent' folder but on 'create' an 'offlone' msg on red background appeared top right.
nginx error.log recorded :
 "PHP message: PHP Catchable fatal error:  Object of class Hm_Site_Config_File could not be converted to string in /usr/local/share/cypht/modules/imap/hm-imap.php on line 47" 
any cue?

thx

### Version & Environment
Cypht latest, Debian stretch {Nginx, Dovecot-imapd}
no database, file-based

### Steps to reproduce
that's already above

**Comment by jasonmunro** [comment]
Should be fixed in the master branch!

**Comment by mpaolo** [comment]
yep, replaced modules/imap_folders/modules.php and now works

thank you a lot :)
