### ISSUE TITLE
opacity on viewing image attachment?

### ISSUE THREAD

**Issue by mpaolo** [jasonmunro/cypht#302]
## 🐛 Bugreport
Hi,
seems that all but the default theme have
`img {
    opacity: .3 !important;
}`
for the img tag, hence an attached img displays like behind a semiopaque glass.
Don't see the reason for that, nor an obvious config-dependent option selected, 
thus I deem it a bug

thx

### Version & Environment
Cypht latest, Debian stretch, nginx+dovecotimapd, vrom Ffox latest on W10pro

### Steps to reproduce
just try to view a sen/received img attachment in non-default theme e.g. *blue

**Comment by mpaolo** [comment]
hm I grabbed the latest, seen the changes, then replaced the new .css ... but see no effect. Thing is, seems the browser still sees the previous .css. Purged browser cache, restarted nginx, close/open browser ... to no avail. Wonder how to convince FFox to drop the cached things, or where the heck it's cached :/
Even in another browser wich never visited the site the .css seems the old one - missing the
`.msg_text_inner img, .apod_image img { opacity: 1 !important; }`
So either it's the nginx or ... am I supposed to re-run the config-gen script?

**Comment by jasonmunro** [comment]
Sorry, should have mentioned that you do need to rerun the config gen script. Part of what that does is copy assets from enabled module sets into the site directory, like the theme css files.

**Comment by mpaolo** [comment]
aha! that did the trick indeed - looks fine now
thanx!
