### ISSUE TITLE
🐛 Replying to a Message shown in "Raw-Mode" will result in empty EMail Text in Compose Form

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#314]
### Replying to a Message shown in "Raw-Mode" will result in empty EMail Text in Compose Form

![image](https://user-images.githubusercontent.com/1238238/52524955-1bd8df80-2ca3-11e9-9ca6-b90c7ba3be24.png)

### Version & Environment

Rev: [19dd3b83287704c87d39734755e952e6c4d811b4](https://github.com/jasonmunro/cypht/commit/19dd3b83287704c87d39734755e952e6c4d811b4)

OS:  [Debian]

### Steps to reproduce
1. Open EMail
2. Press "Raw" Button
3. Press Reply
4. Observe empty Text Field, where you would suspect the original EMail
5. ...
6. Profit

Note: Using Inline View
Note: using Text Emails as default

**Comment by jasonmunro** [comment]
fix pushed to master. If you reply to a message you are viewing in raw mode, the raw message content will be the reply body.

**Comment by ulfgebhardt** [comment]
<3
