### ISSUE TITLE
🐛 [Inline View] is broken with latest master

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#316]
### [Inline View] is broken with latest master

EMails are always opened as standalone, any InlineView Option has no effect

### Version & Environment

Rev: [19dd3b83287704c87d39734755e952e6c4d811b4](https://github.com/jasonmunro/cypht/commit/19dd3b83287704c87d39734755e952e6c4d811b4)
Latest Version know working [9aa7cec4f612375089804165a5f9f936259a3181](https://github.com/jasonmunro/cypht/commit/9aa7cec4f612375089804165a5f9f936259a3181)

OS:  [Debian]

### Steps to reproduce
1. Enable InlineView
2. Open Email
3. No InlineView - EMail is opened standalone
4. ...
5. Profit

**Comment by jasonmunro** [comment]
This is likely a javascript error with the recent switch from zepto to cash. Once I have a fix I will l let you know (I'm also going to see about building a selenium test for this).

**Comment by jasonmunro** [comment]
Should be fixed and I added a selenium test

**Comment by ulfgebhardt** [comment]
<3 ur the best!
