### ISSUE TITLE
ANNOUNCEMENT: new install/upgrade step

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#320]
The composer-issue-311 branch has been merged into master. This change requires composer to be used as part of the install and update process to manage our PHP dependencies. The new command is:
```
composer install
```
Which needs to be run inside the Cypht directory. I have created an "Announcements" wiki page for stuff like this (https://github.com/jasonmunro/cypht/wiki/Announcements), but will also create a temporary issue like this one for similar changes.

**Comment by ehanuise** [comment]
Just reinstalled to go to the latest version, and followed https://cypht.org/install.html
the composer step is not yet mentioned there, so it failed until I foudn this.
=> update https://cypht.org/install.html to add the composer install step ;-)
