### ISSUE TITLE
yahoo mails not appearing in combined folder

### ISSUE THREAD

**Issue by Razvan0925** [jasonmunro/cypht#324]
## 🐛 Bugreport
Yahoo mails are not appearing in combined folder. Also they are slow when opened under Emails section. Other mail vendors work fine (gmail, outlook, cpanel mail servers).

**Comment by jasonmunro** [comment]
Confirmed. This appears to be a bug with the Yahoo IMAP server, however I have a work around that I will push shortly. Not sure what we can do about the performance issues - seems their service is just really slow :/

**Comment by jasonmunro** [comment]
Fix pushed to the master branch. Thanks for the report!

**Comment by jasonmunro** [comment]
I believe this is resolved so I'm going to close this issue. If not, please re-open or file a new one. Thanks!
