### ISSUE TITLE
UX suggestions

### ISSUE THREAD

**Issue by Razvan0925** [jasonmunro/cypht#325]
## 🗣 Suggestion
I have a few UX suggestions as I use this app everyday:
- When selecting multiple mails and click Read, they should remain selected, currently they get unchecked;
- Everything folder unread counter is not working; Unread folder counter is not updating unless you open the folder;
- Desktop notifications are a must have.

Keep up the good work :)

**Comment by jasonmunro** [comment]
> When selecting multiple mails and click Read, they should remain selected, currently they get unchecked;

I'm not sure I understand the use case here. Why do you want them to remain checked?

> Everything folder unread counter is not working; Unread folder counter is not updating unless you open the folder;

The everything folder counter only appears in the page title after loading is complete, seems to be working correctly here. The unread folder has 2 counters, one in the title that will update after a refresh, and one in the folder list that should update about once a minute regardless of what page you are on. This is also working properly for me. Can you explain a bit more what broken behavior you are seeing?

> Desktop notifications are a must have.

We support these, but looks like I never added the module set to the sample ini file! add this to your hm3.ini:

`modules[]=desktop_notifications`

and rerun your config_gen.php script and they should be enabled. I will get that added to the sample ini file. Thanks for the feedback!

**Comment by Razvan0925** [comment]
> > When selecting multiple mails and click Read, they should remain selected, currently they get unchecked;
> 
> I'm not sure I understand the use case here. Why do you want them to remain checked?
> 
That's the way it works in most email clients (gmail, yahoo, outlook). For me it is usefull because I receive many mails with notifications from servers that I manage, and once a day I select those mails, mark as read and delete them.
Another small thing is that in other email clients the selection toggle button, even if you have a few items selected, toggles between all and none, it does not inverse your selection :)
> > Everything folder unread counter is not working; Unread folder counter is not updating unless you open the folder;
> 
> The everything folder counter only appears in the page title after loading is complete, seems to be working correctly here. The unread folder has 2 counters, one in the title that will update after a refresh, and one in the folder list that should update about once a minute regardless of what page you are on. This is also working properly for me. Can you explain a bit more what broken behavior you are seeing?
> 
Just rechecked, you are right, it is working as you detailed, nothing broken :)
> > Desktop notifications are a must have.
> 
> We support these, but looks like I never added the module set to the sample ini file! add this to your hm3.ini:
> 
> `modules[]=desktop_notifications`
> 
> and rerun your config_gen.php script and they should be enabled. I will get that added to the sample ini file. Thanks for the feedback!

I have tried it but it is not working for me. I get an error in the console:
```
Uncaught (in promise) PushError: permission request declined 
```
If it is working for you, maybe it's on my side. I will try to fix it and I will share what I've found.

**Comment by dumblob** [comment]
>Another small thing is that in other email clients the selection toggle button, even if you have a few items selected, toggles between all and none, it does not inverse your selection :)

use case | toggle all or none | invert toggle
---|---|---
nothing selected and want to select all | very easy | very easy
nothing selected and want to select none | very easy | very easy
something selected (small amount as the selection is manual) and want to select all | very easy | very easy (click on the folder or pager and click on toggle)
something selected (small amount as the selection is manual) and want to select none | very easy | very easy (click on the folder or pager)
want to invert selection | **impossible** | very easy

From my point of view would be a nonsense to change the current behavior or even bloat the UI by adding an additional button.

**Comment by jasonmunro** [comment]
I have to agree I also like the inverse behavior better than a standard toggle all :) However I have no issue with "leave checked items checked" after a message operation. @Razvan0925 insofar as the push error, pretty sure that is a browser setting situation. We outsource handling that to the push.js include, but it _should_ prompt you the first time it wants to push a notice and it needs to be accepted or it ends up on a browser black-list (in chromium at least).

**Comment by Razvan0925** [comment]
The "leave checked items checked" would be nice for me, for the selection toggle I agree with you.
The push notifications is working now, it seems the browser refuses to push notification on non-secure or insecure connections, it should have been obvious :grin:

**Comment by jasonmunro** [comment]
checkboxes are no longer reset after a message action https://github.com/jasonmunro/cypht/commit/d23605b96159beac12dc49dbb0f0962eec0f8334

**Comment by Razvan0925** [comment]
Another suggestion: I don't like the current notifications as they are covering the topbar buttons. Toast notifications would be a lot nicer.

**Comment by jasonmunro** [comment]
@Razvan0925 how about something like this:
![sys_msg](https://user-images.githubusercontent.com/3793556/54776323-dd0d4200-4bdd-11e9-86f4-41745ab54b30.png)

**Comment by Razvan0925** [comment]
> @Razvan0925 how about something like this:
> ![sys_msg](https://user-images.githubusercontent.com/3793556/54776323-dd0d4200-4bdd-11e9-86f4-41745ab54b30.png)

Yes, it is nice :smiley: I think it will look nice on desktop too

**Comment by jasonmunro** [comment]
changes pushed to master for user message formatting

**Comment by jasonmunro** [comment]
@Razvan0925 I think your original concerns have all been addressed, so I'm going to close this issue. I like to keep issues as specific and focused as possible (it just helps me stay organized). Fee free to open new issues for other UI suggestions, I appreciate the feedback!
