### ISSUE TITLE
github module details missing

### ISSUE THREAD

**Issue by ScrumpyJack** [jasonmunro/cypht#328]
## 💬 Question
What's the cypht Authorization callback URL that I need to use for this module?

**Comment by jasonmunro** [comment]
Sorry about that, I just added it to the github.ini example file here: https://github.com/jasonmunro/cypht/blob/master/modules/github/github.ini

**Comment by ScrumpyJack** [comment]
got it. Here is an example of what to use:
```
[github.com]
client_id=from github settings > developer settings > New Oauth App
client_secret=from github settings > developer settings > New Oauth App
redirect_uri=https://you_cypht_url/
auth_url=https://github.com/login/oauth/authorize
token_url=https://github.com/login/oauth/access_token

**Comment by ScrumpyJack** [comment]
Hey Jason, could you create a list or repos to "subscribe" to so we don't have to add them in manually?
Lazy, I know...

**Comment by jasonmunro** [comment]
Not sure what you mean, like a pre-defined list for the site? or the ability to upload a list to add? We could also use the github search api and create a search dialog that you could add from ...

**Comment by ScrumpyJack** [comment]
Sorry, I meant a list of the user's own repos. Not a big deal

**Comment by jasonmunro** [comment]
ah, that is a good idea, I will look into it.

**Comment by jasonmunro** [comment]
I'm going to open a new issue for defaulting to the user's repo list when connecting with Github. Since the original question is answered (and the sample ini file is updated with the urls). I'm going to close this one. Thanks for the feedback!
