### ISSUE TITLE
enable gitter for this project

### ISSUE THREAD

**Issue by ScrumpyJack** [jasonmunro/cypht#329]
## 🚀 Feature
get https://gitter.im/ and add cypht room linked to this project

**Comment by jasonmunro** [comment]
I have not tried gitter before but why not. Just created a cypht room, here is the link: https://gitter.im/cypht-org/community

**Comment by ScrumpyJack** [comment]
Maybe put it on https://cypht.org somewhere ?

**Comment by jasonmunro** [comment]
Good idea, I will do that

**Comment by jasonmunro** [comment]
added a contact page with links to github issues, irc, gitter, and my E-mail contact.
