### ISSUE TITLE
add mobile web app capable meta tags

### ISSUE THREAD

**Issue by Razvan0925** [jasonmunro/cypht#330]
## 🚀 Feature
Add mobile web app capable meta tags to be able to install the app on mobile and have the browser topbar disappear.
I think the following would be enough:
```
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
```

**Comment by jasonmunro** [comment]
Great idea! I have never heard of this before. Tested out on android and it works great. Changes added to the master branch. Thanks!
