### ISSUE TITLE
Dual license as LGPL for Tiki

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#333]
Add LGPL license support for easier Tiki integration (https://tiki.org/HomePage)

**Comment by marclaporte** [comment]
Thanks Jason!

So I looked at https://github.com/jasonmunro/cypht/blob/master/composer.json and https://packagist.org/packages/html2text/html2text would need an adjustment. Do you see any others?

FYI to the Cypht community, here is the plan: https://dev.tiki.org/Cypht-integration

**Comment by jasonmunro** [comment]
After much thought on this, I think the right thing to do here is re-license Cypht as LGPL instead of GPL. While it's possible to dual license LGPL and GPL, it does not make a lot of sense to do so. The LGPL is a bit of an odd license as it's focus is on 'libraries" as opposed to stand alone programs, but it protects what I care about (Cypht remains free as in beer and speech), and it facilitates integration with the Tiki project which is something else I really care about :)

**Comment by marclaporte** [comment]
@jasonmunro : fantastic!  It's simple and will make it easy to share some code.

Tiki is LGPL version 2.1.

Thank you very much!!

**Comment by jasonmunro** [comment]
Finally getting around to this, and I can confirm html2text is the only dependency in Cypht that is going to be a problem. I can remove it and replace it with some home grown code that is adequate enough, but sadly it won't do as robust a job formatting the plain text to represent the HTML as this library does.

**Comment by dumblob** [comment]
@mtibben would you be ok to relicense `html2text` as LGPL or something compatible?

**Comment by marclaporte** [comment]
@jasonmunro Let's try to solve license issue to get best code and to participate upstream.

I was part of a team that this did this for Bootstrap: https://github.com/twbs/bootstrap/issues/2054

My experience: most people are just as happy with any Open Source license, and most agree to switch to a license which permits the broadest adoption.

Libraries nowadays are mostly MIT-licensed.

Thanks!

**Comment by jasonmunro** [comment]
@marclaporte Just planning a contingency in the case that the author has no interest in dual/changing licenses. We don't use this code a ton, but it does a nice job. I can probably do something decent in 10 or so lines of code, but most importantly I cannot move forward with this license change until this bit is resolved as you are aware because it is a license violation to do so.

**Comment by mtibben** [comment]
> @mtibben would you be ok to relicense `html2text` as LGPL or something compatible?

See https://github.com/mtibben/html2text/issues/71 - you'll need to ask the original author to relicense the code at http://www.chuggnutt.com/html2text

**Comment by marclaporte** [comment]
@jasonmunro : understood.

I already reached out to Jon Abernathy (@chuggnutt). We'll start the process to reach out to all contributors. If we are not ready in time, we can do a release with 10-lines-of-code-interim-solution. And hopefully, it the next release, we'll restore html2text, and even make contributions :-)

If it doesn't work out, we could set it up so 10-lines-of-code becomes built-in solution but end users can easily install additional dependencies themselves. If present, it would override. We have tools in Tiki to help with this: http://doc.tiki.org/Packages
It would be overkill for just this use case, but there will be other use cases where this could be nice. Ex.: https://github.com/jasonmunro/cypht/issues/382

Thanks!

**Comment by jasonmunro** [comment]
work around is in place. It's closer to 30 lines of code but it also seems to be working a bit better than I planned :) (still not nearly as good as html2text)

**Comment by marclaporte** [comment]
There is also https://packagist.org/packages/soundasleep/html2text
