### ISSUE TITLE
install docs miss the composer step

### ISSUE THREAD

**Issue by ehanuise** [jasonmunro/cypht#336]
## 🐛 Bugreport
Just reinstalled to go to the latest version, and followed https://cypht.org/install.html
the composer step is not yet mentioned there, so it failed until I found issue #320 
=> update https://cypht.org/install.html to add the composer install step ;-)

**Comment by yvesdaxmaz** [comment]
The installation script which is on the https://cypht.org/install.html contains line which run  `composer install` when that script is executed you don't have to execute second time `composer install`
```
# unpack the archive
unzip master.zip

# run composer
cd cypht-master && composer install && cd ..
```

**Comment by ehanuise** [comment]
totally missed that one, thanks :)
