### ISSUE TITLE
cypht forces selection of sending account

### ISSUE THREAD

**Issue by outbackdingo** [jasonmunro/cypht#338]
## 💬 Question
why when i click reply doesnt cypht select the proper account to reply from, i always have to select it from the drop down, if i forget, the email gets sent changing the original email to the new. this is kinda foolish in 2019 when a web client cant determine the proper reply from address.

**Comment by jasonmunro** [comment]
This works properly when you have profiles setup, however I can confirm it does not work as expected when there are no profiles. I will address.
