### ISSUE TITLE
how do we explicitly allow settings to be saved on the server

### ISSUE THREAD

**Issue by outbackdingo** [jasonmunro/cypht#339]
## 💬 Question

Settings are not saved permanently on the server unless you explicitly allow it. If you don't save your settings, any changes made since you last logged in will be deleted when your session expires or you logout. You must re-enter your password for security purposes to save your settings permanently. 

So how the heck do we explicitly allow it, it keeps nuking my whole configuration

**Comment by jasonmunro** [comment]
The short answer is we don't. I'm well aware of the usability concerns around this behavior, however it was a design decision to ensure privacy and security knowing the trade offs. If your login session is timing out prematurely causing you to lose settings before you have a chance to navigate to Settings -> Save, there are some things you could tweak in PHP and Cypht to make sure your session continues to be kept alive.
