### ISSUE TITLE
SMTP servers dissappear after log out

### ISSUE THREAD

**Issue by ghost** [jasonmunro/cypht#340]
This is still happening as of today in the latest git ... logout of ui after saving multiple smtp services, login, all but 2 are gone... i have 5 accounts in one domain. each is a different username@domain.com with separate password, it seems to only affect these accounts.

**Comment by jasonmunro** [comment]
This should be fixed in the master branch

**Comment by jasonmunro** [comment]
Going to close this as I believe it is fixed and I have not received any feedback for several months. If this is still a problem please feel free to re-open.
