### ISSUE TITLE
IMAP Sent-Folder ignored - other clients use correctly

### ISSUE THREAD

**Issue by zerobulfa** [jasonmunro/cypht#343]
## 🐛 Bugreport
hi, 

maybe its not a bug and I'm only stupid - but when I add a IMAP account the "Folder Sent Settings" will be ignored. ~~Trash is working~~, but if I compose a mail in won't appear in the Sent-Folder. If I sending mails from my Thunderbird or Android-K9 the clients are use the default Sent-Folder. The mails were send and I can reply, forward new mails etc. (works fine :) ) 

Was looking in the Code, but find nothing hardcoded or something to find the "failure". Only when I log my webserver (apache2) I see hes trying to get:

`11.222.33.44 - - [07/May/2019:16:34:45 +0200] "POST /?page=message_list&list_path=sent HTTP/1.1" 200 1012 "https://mail.example.com/?page=message_list&list_path=sent" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"`

If there maybe a problem "my" sent-folder @ IMAP is "Sent" and not "sent"?
I can choose the "Sent"-Folder (Settings > Folders > Sent Folder:). Profil is set up and default (only one user) - I can crate new Folders etc. - No errors in Logs so far. 

### Version & Environment

OS:  4.9.0-8-amd64 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
Mail/Server: 
postfix/stable,now 3.1.12-0+deb9u1 
dovecot-imapd/stable,stable,now 1:2.2.27-3+deb9u4 
PHP 7.0.33-0+deb9u3 + 
apache2/stable,stable,now 2.4.25-3+deb9u7
php7.0-intl/stable,stable,now 7.0.33-0+deb9u3

Cypht-Version: last version two days ago from  https://github.com/jasonmunro/cypht/archive/master.zip

regards,
zb

**Update**: Trash don't work too - its empty for Cypht but on the IMAP-Folder still there

**Comment by jasonmunro** [comment]
Sent and Trash are working for me so I'm not sure what is wrong. You are correct in thinking you have to have a profile that associates an IMAP server with an SMTP server in order for saving in Sent to work, and you need to assign those of course in the Settings -> folders page. It might be worth enabling debug mode and keeping any eye on the PHP log (we log a lot more info in debug mode).

Info on debug mode:
https://github.com/jasonmunro/cypht/wiki/Troubleshooting-Login-Issues

**Comment by zerobulfa** [comment]
Hi,

thx for ur reply.

Here is what I got if I update the Sent-Folder-Settings when debug is on:

> ==> mail.example.de-error.log <==
[Thu May 09 09:28:44.944495 2019] [:error] [pid 12813] [client 62.245.XX.YY:22078] Array\n(\n    
[0] => Using Hm_PHP_Session with Hm_Auth_DB\n    
[1] => Using file based user configuration\n    
[2] => Using sapi: apache2handler\n    
[3] => Request type: AJAX\n    
[4] => Request path: /\n    
[5] => TLS request: 1\n    
[6] => Mobile request: 0\n    
[7] => Page ID: ajax_imap_unread\n    
[8] => Redis enabled but not supported by PHP\n    
[9] => Memcached enabled but not supported by PHP\n    
[10] => CACHE backend using: noop\n    
[11] => LOGGED IN\n    
[12] => CACHE: saving "imap0" using noop\n    
[13] => PHP version 7.0.33-0+deb9u3\n    
[14] => Zend version 3.0.0\n    
[15] => Peak Memory: 2048\n    
[16] => PID: 12813\n    
[17] => Included files: 64\n)\n, referer: https://mail.example.de/?page=folders&imap_server_id=0

Don't see what´s helping me - maybe 9/10 but I don't think its necessary?

regards,
zb

**Comment by zerobulfa** [comment]
Hi,

I switched to another webclient - works for me like expected.

Thanks for you time,
regards,
zb

**Comment by jasonmunro** [comment]
@zerobulfa sorry to hear that but I understand. I appreciate that you checked out the project. If I run into this again and can reproduce/fix it I will update this issue.

**Comment by outbackdingo** [comment]
Still occurs on my setup as of todays git rev

**Comment by apezio** [comment]
this happens to me also.

Sent shows up in my imap Sent folder but not the Sent folder of Cypht.

* GIT VERSION: 10813

I have two imap and two smtp accounts.

Sometimes mail from one account (but not the other) will show up in sent.  but later it's gone again.
