### ISSUE TITLE
nothing saved in sent folder after composing email

### ISSUE THREAD

**Issue by ghost** [jasonmunro/cypht#345]
Nothing is saved in the sent folder after composing and sending emails in the web ui, works fine for all other clients... phone and other.

**Comment by jasonmunro** [comment]
Just pushed a potential fix if you could give it a try that would be great.

**Comment by jasonmunro** [comment]
Just added some additional debugging to the saving process. In debug mode we should get some more information about why this isn't working for you.

Another possible issue I was thinking might cause this: If you deleted and recreated an IMAP or SMTP server it could "corrupt" the profile such that it fails to properly associate the servers together. Might be worth trying to delete and recreate your profile to see if that has any effect.

**Comment by jasonmunro** [comment]
Just to follow up, my last comment was inaccurate. Profiles correctly handle when a server is deleted, however special folder assignments do NOT handle this properly. I have an issue to address that situation and hope to push a fix within a week.

**Comment by jasonmunro** [comment]
Issue #349 will address this problem so I'm closing this one to keep things tidy.
