### ISSUE TITLE
Deleting an IMAP server can break special folder associations

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#349]
Deleting an IMAP server can cause the association of special folders to be "offset" because they are using server ids which can change between login. We need to:

- change the data structure used by the imap folders module set to use the IMAP server name and username to associate the special folders instead of the id.
- re-save the details maybe as a one time check on login so it can be done without user interaction. Need to think about that. Worst case this becomes a non-backwards compatible fix and users will have to re-assign their special folders.

**Comment by dumblob** [comment]
>Worst case this becomes a non-backwards compatible fix and users will have to re-assign their special folders.

If there will be a semi-automated way of backing them up (or exporting) in a human (not necessarily machine) readable format (e.g. some txt or structured JSON or SQL dump or you name it) either as the user, then I would say there is no obstacle and we don't need to preserve backward compatibility and just add a huge warning to the documentation for the last release supporting the old behavior and also to the installation/init setup procedure of the newer versions for the next 12 months while copying the current DB (or just the relevant tables) somewhere to avoid potential loss of user settings.

**Comment by kroky** [comment]
I think https://github.com/jasonmunro/cypht/pull/454 should fix this issue.
