### ISSUE TITLE
The Big Problem is that you guys usually leave the Projects!

### ISSUE THREAD

**Issue by masall** [jasonmunro/cypht#350]
## 🗣 Suggestion

The Big Problem is that you guys usually leave the Projects!
E-mail clients are very serious things to be abandoned!

**Comment by dumblob** [comment]
If you know about an organization which would formally take over the project and which would hire (and pay) programmers if needed, then definitely go ahead and list them here.

Or if you're a private sponsor/investor, don't hesitate and say so and we'll assemble some minimal team to maintain and develop Cypht for the next many years.

If you're just suggesting we shall think about the [bus factor](https://en.wikipedia.org/wiki/Bus_factor ) then we're glad you're aware of this issue and we're open for ideas how to come across that.

If your "Suggestion" is about something else, just say so directly - we'll do our best to listen.

**Comment by jasonmunro** [comment]
I'm not sure I understand, this project is not abandoned. I have been working on this code base for 5 years, and my prior E-mail projects for 10 years before this one. It is however an entirely volunteer effort. I have a family and a full time job and sometimes I just don't have the time to spend on it. The last few weeks have been extremely busy for me and while I have not been doing as much coding as I would like, its not accurate to say this project is abandoned or that it will be anytime soon. In fact I'm actually planning on starting a new release cycle in the next week or so.

**Comment by Yamakasi** [comment]
I think someone didn't know how to get rid off this own frustration after he found out you have to work/learn how to understand code., this is not IRC ;)

Keep up @jasonmunro no worries :)

**Comment by marclaporte** [comment]
Beyond @jasonmunro's outstanding dedication to the project
- 500+ stars and 70+ forks on https://github.com/jasonmunro/cypht 
- Cypht was picked for WikiSuite: https://wikisuite.org/Cypht
- There are thousands of installs on Packagist: https://packagist.org/packages/jason-munro/cypht
- A new website is in the works

@masall: There is a link on https://cypht.org/contact.html to the chat room. Please do get involved!

**Comment by jasonmunro** [comment]
@masall I appreciate your concerns but as I mentioned this project is not abandoned nor will it be anytime soon if I can help it. Also thanks to everyone who chimed in with support. If you want to get involved any and all contributions to the project are welcome!

**Comment by marclaporte** [comment]
@masall Please join the chat: https://gitter.im/cypht-org/community

We need testers for all the features: https://github.com/cypht-org/cypht/releases
