### ISSUE TITLE
Available API endpoints

### ISSUE THREAD

**Issue by TetrisIQ** [jasonmunro/cypht#356]
# 💬 What API Endpoints are available
Currently, I try to use the API to get the number of all unread E-Mails in Python. The first step in the authorization works (getting the hm_id and hm_session) but the second step is not working at all, I'll get the login page back. This is the python code.

````python
payload = {
    "hm_id": hm_id,
    "hm_session": hm_session,
    "api_login_key": hm_api_key,
}
r = requests.post(url + "?page=process_api_login/", data=payload, headers=HEADER)
````

So I'm not sure if the 'page=process_api_login' endpoint is right here. And I'm not sure what other endpoints exists, (for example to get all unread mails or all mails). Is the API designed for that kind of used.

Thanks for help

Regards TetrisIQ

**Comment by jasonmunro** [comment]
@TetrisIQ sorry for the late response. The api login process is only intended to supply a way to automatically be logged into Cypht - not as an API to get things like a list of unread E-mail. You may want to look at something like JMAP for a modern E-mail API.

**Comment by TetrisIQ** [comment]
Thanks for your response and for the hint to JMAP. I will take a look on it.
