### ISSUE TITLE
unable to add SMTP servers: Cound not add server: php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by nekromoff** [jasonmunro/cypht#364]
## 💬 Question

Cound not add server: php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by nekromoff** [comment]
imap and others work fine

**Comment by nekromoff** [comment]
Any ideas? I have now tried it with two different hostings and the same error, I am just unable to add any SMTP server (tried multiple, different settings, SSL, TLS, 465, 567, 25 etc.).

**Comment by jasonmunro** [comment]
I'm unable to reproduce this so I'm not sure what is going on. It's the same process used to add an IMAP server (we use PHP's fsockopen() to attempt a network connection to the server + port). I just tested smtp.gmail.com port 465 with TLS and it worked without issue.

**Comment by nekromoff** [comment]
I will put PHP in full error mode and report back.

**Comment by jasonmunro** [comment]
you may also want to remove the '@' character here:

https://github.com/jasonmunro/cypht/blob/master/modules/smtp/modules.php#L243

This stifles PHP warnings (which are likely the same as $errstr) but worth trying to see if it provides any additonal clues.

**Comment by nekromoff** [comment]
Must have been problem with some of the PHP modules, everything works after upgrade.

**Comment by jasonmunro** [comment]
Glad to hear you got this sorted. Thanks for the feedback and don't hesitate to let us know if you have other issues/questions/suggestions!
