### ISSUE TITLE
When picking emails in lists, Copy and Move should work everywhere: All Mails, simple search and advanced search.

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#371]
![2020-02-01_030910](https://user-images.githubusercontent.com/1004261/73589157-8b417380-44a0-11ea-8ef0-c4953ce0347d.png)

**Comment by jasonmunro** [comment]
Agreed. I _think_ most of the guts of copy/move will "just work" once they are added to the search results. Now that I say that maybe there was a reason I left them off ...  I will take a closer look and let you know.

**Comment by marclaporte** [comment]
"I will take a closer look and let you know."

I suggest to let the junior developers learn with this. Keep your time for the hard stuff :-)

**Comment by jasonmunro** [comment]
Thanks @yvesdaxmaz for the PR. Merged to master

**Comment by yvesdaxmaz** [comment]
I am very happy to hear that :smile: :+1:

**Comment by marclaporte** [comment]
As of now, simple search doesn't not work.

Advanced search now works but:
![2020-10-06_110333](https://user-images.githubusercontent.com/1004261/95219994-fc6dbf00-07c3-11eb-8e4c-461a3d2ab08c.png)

![2020-10-06_104953](https://user-images.githubusercontent.com/1004261/95220064-0f808f00-07c4-11eb-9641-477dde942af6.png)

**Comment by marclaporte** [comment]
It's better but still not 100% reliable. I need to wait for page to be fully loaded before picking emails. I showed @kroky and he has an idea of the issue.

**Comment by marclaporte** [comment]
One more fix: https://github.com/jasonmunro/cypht/pull/587
