### ISSUE TITLE
Support of IPv6?

### ISSUE THREAD

**Issue by mohammaddarweesh** [jasonmunro/cypht#379]
## 💬 Question

does Cypht support IPv6?

**Comment by jasonmunro** [comment]
Good question! I honestly don't know :) It _should_, but I would have to do some testing before I can say that for sure.

**Comment by jasonmunro** [comment]
Accessing Cypht using the localhost IPV6 IP on Debian ([::1]) appears to work fine!
![ipv6](https://user-images.githubusercontent.com/3793556/81102313-15044100-8ed5-11ea-9937-024e32eafa60.png)
