### ISSUE TITLE
Interface language clean up

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#39]
Many of the interface languages were generated with the google translate api - from what I have been told they are hilariously bad. Remove these and leave the 2 (?) actual translations.

Add missing strings per the debug output for each page to the remaining translation files

**Comment by jasonmunro** [comment]
fixed in master

**Comment by mat-m** [comment]
Hello
I did a fresh translation for french, added it in the language folder, but even a php ./config_gen.php did not update the language list in the settings. What do I miss ?

**Comment by jasonmunro** [comment]
Thanks for doing this! There is a function in the core modules that defines the list of available langs:
https://github.com/jasonmunro/hm3/blob/master/modules/core/functions.php#L50
So once you add to that it should be available in the settings.

**Comment by mat-m** [comment]
Found and fixed.
Some issues about translations: 
* Date (Mont, Year) in calendar is not translated
* Some Messages list titles are not translated (although their entry in the left menu is): Flagged, Unread, Everything, All Email
* In the homepage: 

> POP3 services are not enabled for this site. Sorry about that!

is not translated, nor the "Update" Link for the timezone

**Comment by jasonmunro** [comment]
Thanks for tracking those down. All of the missing translations you mentioned should now be fixed.

**Comment by dumblob** [comment]
I just spotted, that the comment on https://github.com/jasonmunro/hm3/blob/master/modules/core/functions.php#L46 doesn't reflect this decision to throw away the Google-translated strings ;)

**Comment by jasonmunro** [comment]
Good catch! Now fixed.

**Comment by jasonmunro** [comment]
mat-m, I would love to merge your corrected French translation when you are ready. Just send me a pull request and I will merge it. Thanks!

**Comment by mat-m** [comment]
The line ` 'Add An E-mail Account' => false,` has disappeared from en.php and is not translated anymore.

**Comment by jasonmunro** [comment]
The problem with the add an email account string, and the copy/move strings, is they are used in multiple places with different capitalization. I'm going to get this cleaned up today. Strings in the lang files that need a leading capital in some cases and lowercase in others will be defined with the capital in the translation file, and I will use css to convert them to lowercase where need be. I will also add the missing download link.

**Comment by jasonmunro** [comment]
Just pushed fixes for everything and merged the latest pull requests WRT to i18n. Thanks everyone for the feedback. If you notice anything else please let me know!

**Comment by mat-m** [comment]
The gear in front of the profiles name has a tip "Edit" which is not translated
Same applies for Edit, Delete and Send To in local contacts.

Since the translations exist, it is more a problem of using it in the code.

**Comment by jasonmunro** [comment]
Good catch! Fixed in https://github.com/jasonmunro/hm3/commit/c0db0ae2c8fb881acb9b0e545e22cfb451d77855
Thanks!

**Comment by jasonmunro** [comment]
Added some new strings today. I think we are getting close to being i18n complete.

**Comment by jasonmunro** [comment]
Another round of strings added to the language files for the latest feature updates

**Comment by jasonmunro** [comment]
Added more strings to the language files. I'm planning a release soon, so if anybody has time to update a language it would be much appreciated!

**Comment by jasonmunro** [comment]
so much for that soon to be created "release" from April 2017! I'm actually thinking about this again, so I will create a more specific issue around translations if need be. I'm trying to remove generic issues that don't get attention and replace them with more specific ones that are easier to deal with, so i"m closing this.
