### ISSUE TITLE
After moving messages to another folder, the interface should show that is has been done

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#392]
1. On a list, I click a bunch of emails, and I click move, and pick the destination folder
2. After working on it, Cypht replies "Messages moved"
3. But I still see them in the list. So I am not fully convinced it worked.

Should we change anything?

Some ideas:

- Indicate "12 messages were moved. Click here to refresh the list"
- Do a full refresh of the list at the end of the operation
- As each message is moved, add an animation of the message disappearing

**Comment by jasonmunro** [comment]
This is I think a bug. Moved messages should be removed from the current listing client side immediately (and restored on failure).

**Comment by marclaporte** [comment]
Related: https://github.com/jasonmunro/cypht/issues/440

**Comment by marclaporte** [comment]
Working fine now. I don't know what commit solved it but we are one step closer to releasing Cypht 1.2 :-)
