### ISSUE TITLE
The advanced search should show the most recent emails first (when too many results)

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#394]
I accept that there are more results than what goes on page 1, but the order is not what I would expect.

![2020-04-29_000446](https://user-images.githubusercontent.com/1004261/80560099-b8bd9080-89ad-11ea-9636-31b141f8566c.png)

**Comment by dumblob** [comment]
I second this proposal as the order shall be the same for most email listings (for better UX).

**Comment by jasonmunro** [comment]
Not sure I follow. Are the results matching the search criteria not in arrival order?

**Comment by marclaporte** [comment]
Indeed.

**Comment by jasonmunro** [comment]
my bad, I misunderstood the problem. The result limit slice is not starting at the right place because the results are unsorted when the slice occurs. Fix pushed to master

**Comment by jasonmunro** [comment]
@marclaporte I will leave this open until you can confirm the fix is good for you. Thanks!

**Comment by marclaporte** [comment]
Ok, thanks to Packagist.org and Tiki CI, this will automatically be in Tiki within a few days, so I will retest then.

Thanks!

**Comment by marclaporte** [comment]
I confirm the fix. Thank you!
