### ISSUE TITLE
Is it possible to filter messages to custom folders?

### ISSUE THREAD

**Issue by ChangePlaces** [jasonmunro/cypht#396]
## 💬 Question
e.g. If the subject contains certain words, or if the body does, or if the sender is a particular address etc I'd like to put messages into particular folders depending on certain criteria. Is this possible? I don't see any mention of filtering in the features nor the modules section

**Comment by marclaporte** [comment]
Hi @ChangePlaces 

Thanks for using Cypht!

Sorry, it's not possible yet, but it's one of the most desired features. I see you added a "Thumbs Up" here: https://github.com/jasonmunro/cypht/issues/9  We are looking for more contributors.

Best regards,
