### ISSUE TITLE
Have a way to indicate default setting, and reset it.

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#399]
When using default settings, users will experience fewer bugs. So when there are issues, resetting to the default can be a quick fix/workaround. And this can lead to better bug reports. 

We did this in Tiki for http://doc.tiki.org/Site-configuration-preferences. I got used to it and miss it in other applications. Basically, it shows user which settings have been modified and lets them reset to default.
![2020-05-06_112459](https://user-images.githubusercontent.com/1004261/81195797-4ee44e80-8f8c-11ea-9303-f4fab1587798.png)

Pàdé even has the concept of a Factory Reset: https://github.com/igniterealtime/pade
![2020-05-06_113325](https://user-images.githubusercontent.com/1004261/81196864-97503c00-8f8d-11ea-957c-24a48d49af9d.png)

This is the lowest priority, so we'll probably never get to it :-)  On the other hand, it's an easy first task to get a developer involved.

**Comment by jasonmunro** [comment]
Good idea and easy to implement

**Comment by marclaporte** [comment]
Done, and there has been a suggestion to change the label: https://gitter.im/cypht-org/community?at=60ef1b1623fd26511db05d76

**Comment by marclaporte** [comment]
@NasserNgandu Please revisit.

**Comment by marclaporte** [comment]
https://github.com/jasonmunro/cypht/pull/560
