### ISSUE TITLE
Help links in emails (ex.: to unsubscribe from a mailing list) should start email from current account

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#400]
![2020-05-11_000427](https://user-images.githubusercontent.com/1004261/81523252-505e9f80-931b-11ea-8967-bf94513ff2ff.png)

**Comment by marclaporte** [comment]
Similar to this, if I reply to or forward an email, it should use the account of that email.

Now, sometimes, it does, but sometimes it uses the default account. It is perhaps linked to https://github.com/jasonmunro/cypht/issues/420 as I noticed that once for a blank message, it was using default account.

**Comment by marclaporte** [comment]
I just tried with master. Issue is still present.

**Comment by marclaporte** [comment]
To reproduce:
# Set up latest Cypht, with multiple accounts
# Subscribe to a mailing list
# Check that the links appear and test them.

**Comment by henrique-borba** [comment]
@jasonmunro The PR only affects IMAP inbox, I will take a look at the POP3 module to make sure if it also need to be updated

**Comment by marclaporte** [comment]
POP3 is low priority: https://github.com/jasonmunro/cypht/issues/452
