### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Master0ne** [jasonmunro/cypht#406]
## 💬 Question
I really had high hopes in this project, because there is absolute no viable alternative (except maybe Nextcloud Mail, but that one has to be considered being in an early stage with some essential functionality still missing) which offers to have multiple accounts visible at the same time in the same browser tab (which is why Roundcube and Rainloop is a no-go for me).

But the lack of updates and information, as well as the incompatibility of the code with PHP versions higher than 7.2 rises concerns if Cypht is still being actively developed.

Is @jasonmunro still around?
Are there any plans or road map for further development?

I am not a programmer / developer, but just a user looking for a proper self-hosted webmail software that can run in a shared webhosting environment, so I am sorry that I can not be of any help and contribute to this project.

**Comment by marclaporte** [comment]
@Master0ne You can help in many ways. Testing, feature requests, bug reports, promotion, etc. Go add hearts to the issues you think should be prioritized. And the time you invest frees up developers to make great code.

The project is doing very well. We have now integrated in Tiki so all Tiki contributors are exposed to it, and as they gain experience, more contributions will come in:
http://dev.tiki.org/Cypht-integration

Beyond Tiki, we are now attracting a lot of developer downloads:
https://github.com/jasonmunro/cypht/issues/311

Email is a special use case: Everyone uses it. So as more developers start using on a daily basis (like I do), we will get a steady stream of contributions.

And some experienced devs will step up to help Jason, who has done tremendous work.

**Comment by marclaporte** [comment]
As everyone can see, we are making great progress: https://github.com/jasonmunro/cypht/commits/master
