### ISSUE TITLE
Redis Socket

### ISSUE THREAD

**Issue by gxf0** [jasonmunro/cypht#410]
I love this mail/rss client. But is it possible to connect via socket to redis? Just found the port settings in the config file

**Comment by Yamakasi** [comment]
Redis is just caching, what do you want/need ? Redis !== Reddit ;)

**Comment by gxf0** [comment]
As I said, just connect via socket, not via port. I tried by setting the port to 0 and setting the server to the socket, ... but it doesn't work. 

hm3.ini:

```
; Configure Redis details below to use it for caching
enable_redis=true
redis_server=/var/run/redis/redis.sock
redis_port=0
redis_index=5
redis_pass=
```

```
root@xf0:~# redis-cli -s /var/run/redis/redis.sock INFO | grep ^db
db2:keys=2957,expires=329,avg_ttl=284817133
db3:keys=936,expires=100,avg_ttl=41470665
db4:keys=52,expires=7,avg_ttl=78548700
```

**Comment by Yamakasi** [comment]
OK, now I understand, why would you connect by socket ? Accesstime ?

**Comment by gxf0** [comment]
Safty, Accesstime and i dont have to deal with passwords ;) Works with wordpress and some other CMS like a charm. So I would like to keep my socket :D

**Comment by jasonmunro** [comment]
@gxf0 Just pushed support for this. Pull the latest master branch, add a `redis_socket=/path/to/file.sock` to your hm3.ini file and rerun the config gen and you should be all set.

**Comment by gxf0** [comment]
thanks a lot, I will check out later!

**Comment by gxf0** [comment]
seems to be fixed :)
