### ISSUE TITLE
No login possible with port number that differs from port 80

### ISSUE THREAD

**Issue by MGoeppl** [jasonmunro/cypht#414]
## 🐛 Bugreport

When using a port different than Port 80 (810 in my case), I can open the login view, but not log in. No error is displayed.
### Version & Environment

Rev: []

OS:  [Apache2, Ubuntu]

**Comment by jasonmunro** [comment]
Well that sounds like a bug :) I will check into it and let you know. Thanks for the feedback!

**Comment by jasonmunro** [comment]
@MGoeppl Just pushed a fix that should resolve the issue. Please re-open this if you are still having problems.
