### ISSUE TITLE
Loose version constraint composer dependencies

### ISSUE THREAD

**Issue by xorti** [jasonmunro/cypht#415]
## 🗣 Suggestion

Loose version composer dependencies in order to use newer versions.

Currently, on composer.json:
```
"paragonie/random_compat": "2.0.18",
"erusev/parsedown": "1.8.0-beta-5",
"christian-riesen/base32": "1.3.2",
"ezyang/htmlpurifier": "4.10.0",
"codeitnowin/barcode": "3.0.3",
```

Suggestion:
```
"paragonie/random_compat": "^2.0.18",
"erusev/parsedown": "^1.8.0-beta-5",
"christian-riesen/base32": "^1.3.2",
"ezyang/htmlpurifier": "^4.10.0",
"codeitnowin/barcode": "^3.0.3",
```

That will allow, for example, to install `ezyang/htmlpurifier` with v4.13.0 that includes some fixes with curly braces in PHP7.4 and PHP8.

Thank you.

**Comment by jasonmunro** [comment]
I'm happy to do this. I presume the leading "^" means this version or newer (I will read up on it). If there are newer compatible versions I'm open to bumping the minimums up as well.

**Comment by xorti** [comment]
I'm doing the PR at this moment! 
There is no need to bump the minimums, composer itself will manage that, and it will be wider the options. The minimums should be bumped only if the cypth code changes and the minimum version for dependencies brake the functionality.

The "^" will allow versions for example in the ezyang/htmlpurifier to be up to <5.0.0. Using "~" will just allow <4.11.0.
