### ISSUE TITLE
Potential attack using "mailto:"

### ISSUE THREAD

**Issue by dumblob** [jasonmunro/cypht#423]
I'm not sure Cypht does anything special with "mailto:" links, but either way it might be interesting to see what threats are lurking around:

https://www.zdnet.com/article/some-email-clients-are-vulnerable-to-attacks-via-mailto-links/

**Comment by jasonmunro** [comment]
Cypht supports mailto links to pre-populate the To, Cc, Bcc, Subject, and Body fields. This specific vulnerability uses the more esoteric attachment parameter to pre-attach a local file which we don't support so we should be good here.
