### ISSUE TITLE
Inbox sort order keeps resetting

### ISSUE THREAD

**Issue by drboom** [jasonmunro/cypht#424]
## 🐛 Bugreport
In the upper, right corner of the inbox page, there is a drop-down that lets me choose a sort order.
Choices include "Arrival [ascending]" and "Arrival [descending]"
Selecting descending sorts the emails in the requested order with the most recent email at the top of the list.
Refereshing the mailbox by using the refresh icon or by the periodic automatic page reload,
causes the sort order to revert to ascending.  But the dropbox still shows descending so,
in order to get it back to descending, I have to change the dropbox to something other than descending
and then change it back to descending.

### Version & Environment
Rev: [https://github.com/jasonmunro/cypht/commit/0c7a095ec0819fa7094d5c9af9191dc945b251f5]
OS:  [Ubuntu 7.5.0-3ubuntu1~18.04]

### Steps to reproduce
1. Navigate to inbox screen
2. Select sort by arrival, descending.  This means most recent email first.
3. Wait for page to refresh.
4. Observe that sort order is by arrival, ascending.  Meaning oldest email first.

**Comment by drboom** [comment]
Actually, it appears that when the refresh happens, the messages aren't sorted in ascending order.  They appear in the order they come in from the POP3 server.  Not sorted at all.

**Comment by marclaporte** [comment]
Related: https://github.com/jasonmunro/cypht/pull/418

**Comment by jasonmunro** [comment]
Just to confirm this is also POP3 specific I think as I don't see this happening with IMAP folder sorting

**Comment by richardneish** [comment]
I'm seeing this or something similar happening with IMAP accounts.  I have three IMAP mail accounts and they don't seem to be sorted per the sort dropdown when I first log in.  Changing the sort order and then changing back produces the sorted result.

**Comment by marclaporte** [comment]
@richardneish @drboom Please retest with latest code as it has changed significantly. Ref.: https://github.com/jasonmunro/cypht/issues/378

**Comment by marclaporte** [comment]
Proposal: Deprecate POP3 support if no one steps up to maintain it
https://github.com/jasonmunro/cypht/issues/452
