### ISSUE TITLE
Sort function only applies to one page of messages

### ISSUE THREAD

**Issue by drboom** [jasonmunro/cypht#425]
## 🚀 Feature
The inbox sort feature only sorts the messages on one page of messages.  Ideally, it would sort over all messages in the inbox.  If an inbox contains more than 20 messages, one expects sorting the first page of results by Arrival, descending to show the newest message.  It does not necessarily display the newest message at all because the newest message may appear on a different page.

**Comment by jasonmunro** [comment]
This works fine for IMAP folders so I presume this is another POP3 related issue?

**Comment by marclaporte** [comment]
Proposal: Deprecate POP3 support if no one steps up to maintain it
https://github.com/jasonmunro/cypht/issues/452
