### ISSUE TITLE
POP3 delete does not work

### ISSUE THREAD

**Issue by drboom** [jasonmunro/cypht#426]
## 🐛 Bugreport

Select several messages.  Click DELETE.  Messages dissapear.  Nothing (like DEL) is sent to the POP3 server.  Next time the mailbox refreshes, the deleted messages reappear.

### Version & Environment

Rev: [https://github.com/jasonmunro/cypht/commit/0c7a095ec0819fa7094d5c9af9191dc945b251f5]

OS:  [Ubuntu 7.5.0]

### Steps to reproduce
1. Connect to a POP3 server
2. Click the checkbox beside a message listing
3. Click the DELETE button in the page header
4. Click OK in the confirmation pop-up
4. Refresh the list.  Or wait for automatic refresh

**Comment by jasonmunro** [comment]
As I have mentioned in other issues, our POP3 support is not very good :) However, deleting should at least work. I will check into it.

**Comment by marclaporte** [comment]
Proposal: Deprecate POP3 support if no one steps up to maintain it
https://github.com/jasonmunro/cypht/issues/452
