### ISSUE TITLE
Stable version for Composer/Packagist

### ISSUE THREAD

**Issue by Yamakasi** [jasonmunro/cypht#427]
## 🐛 Bugreport

Maybe it's good to create a stable version for composer ?

``` 
$ composer require jason-munro/cypht

In InitCommand.php line 785:

  Could not find a version of package jason-munro/cypht matching your minimum-stability (stable). Require it with an explicit version constraint allowing
   its desired stability.

```

**Comment by marclaporte** [comment]
Indeed. As soon a next major version will be released.

Related: https://github.com/jasonmunro/cypht/issues/311

**Comment by Yamakasi** [comment]
> 
> 
> Indeed. As soon a next major version will be released.
> 
> Related: #311

Can be the current version without any problem. Never wait with such things for no reason.

**Comment by marclaporte** [comment]
@Yamakasi Are you suggesting the latest stable version https://github.com/jasonmunro/cypht/releases/tag/v1.1.0 should be added to Packagist?

**Comment by Yamakasi** [comment]
> 
> 
> @Yamakasi Are you suggesting the latest stable version https://github.com/jasonmunro/cypht/releases/tag/v1.1.0 should be added to Packagist?

Sure I would even do 1.2.0 but 1.1.0 as latest tag, then you are fine for now.

**Comment by marclaporte** [comment]
@jasonmunro addressed that question here: https://github.com/jasonmunro/cypht/issues/311#issuecomment-476941374

"We would have to back-port the composer changes to the prior release to accomplish this with 1.1.0 - something I would rather not do. Instead, lets start the process of a 1.2.0 release"

**Comment by Yamakasi** [comment]
> 
> 
> @jasonmunro addressed that question here: [#311 (comment)](https://github.com/jasonmunro/cypht/issues/311#issuecomment-476941374)
> 
> "We would have to back-port the composer changes to the prior release to accomplish this with 1.1.0 - something I would rather not do. Instead, lets start the process of a 1.2.0 release"

No reason for it, seriously.

**Comment by marclaporte** [comment]
@Yamakasi  Can you change your minimum-stability for now?

Let's all help release 1.2!

**Comment by marclaporte** [comment]
Done for 1.3.0!
https://packagist.org/packages/jason-munro/cypht#v1.3.0

Downloads (installs) for all versions:  35 823 :-)

**Comment by marclaporte** [comment]
We are at nearly 100 000 installs on https://packagist.org/packages/jason-munro/cypht!

**Comment by marclaporte** [comment]
We have passed 100k installs for Cypht! https://packagist.org/packages/jason-munro/cypht
