### ISSUE TITLE
HTML (GMail)Mails runs in an "Server Error"

### ISSUE THREAD

**Issue by csuno** [jasonmunro/cypht#428]
## 🐛 Bugreport
When i disable "Prefer text over HTML when reading messages" in settings and try to load an HTML Mail, it doesnt open anything, and just creates an "Server Error" message...

With "Prefer text over HTML when reading messages" enabled, the mail is loaded as text normaly... 

Rev: [where can i find my actual version?]
OS:  DOCKER (https://hub.docker.com/r/sailfrog/cypht-docker/)

**Comment by jasonmunro** [comment]
Looks like that docker image has not been updated in a long time. I used to have it automated but something changed and broke that. I'm working on creating a new build form current master now. I am unable to reproduce the error you are seeing locally with a couple Gmail accounts I have tested so hopefully just getting to the latest code will fix this up.

**Comment by jasonmunro** [comment]
The Docker image has been rebuilt, could you give that a try and see if it fixes this issue?
