### ISSUE TITLE
UTF8 corruption when replying as text to HTML message part

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#429]
1. Send an HTML email from Gmail with http://kermitproject.org/utf8.html to Cypht
2. Reply to the HTML part as TEXT and the reply text is mangled.

This only happens when replying to an HTML prt with outbound mail set to TEXT. All other combinations work fine.

**Comment by jasonmunro** [comment]
Update - actually replying to the HTML part when using outbound of MARKDOWN also fails.

**Comment by marclaporte** [comment]
With 1.9 million downloads, maybe this can help: https://packagist.org/packages/soundasleep/html2text

**Comment by jasonmunro** [comment]
> php: >=7.0

**Comment by jasonmunro** [comment]
@marclaporte should be fixed in master. While we can't use the package you posted, it is a good reference for potential issues around HTML -> TEXT conversion. I happened to find this fix elsewhere but still very useful so thanks for the post. I will leave this open for you to confirm on your end the problem is resolved.

Thanks!

**Comment by marclaporte** [comment]
About "php: >=7.0": We can use an older version https://packagist.org/packages/soundasleep/html2text#0.5.0 until our requirements increase.

**Comment by marclaporte** [comment]
Ah wait, older version are licensed EPL-1.0, and I don't know off-hand if it's compatible. In any case, we'll sooner or later increase minimum requirements, and the lib will become an option at that point: https://github.com/jasonmunro/cypht/issues/431

**Comment by jasonmunro** [comment]
Well what we have works fine for now and honestly is not very different than what this third party code does.

**Comment by marclaporte** [comment]
@jasonmunro understood.

I think we can close this issue. It works for me with the newest code.

Thanks!
