### ISSUE TITLE
Support Eudora Internet Mail Server (EIMS)

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#430]
This mail server has some quirky behavior we added work arounds for to Hastyamil 2. Need to revisit that and add them to Cypht.

**Comment by jasonmunro** [comment]
First fix for EIMS folder handling is here: https://github.com/jasonmunro/cypht/commit/f26f9c0ea3c1aaeae089faab7ae8b88c773a733c

EIMS does not support various super handy flags that indicate if a folder 1. can have sub-folders, and 2. actually does have them. Also this IMAP server is pretty old school in that a folder with sub-folders can't have mail. This is not super uncommon but more modern IMAP servers like dovecot allow folders to have both. 

While I work through EIMS compatibility issues I'm disabling them by default with a switch here:

https://github.com/jasonmunro/cypht/blob/master/modules/imap/hm-imap.php#L71

If you want to test or enable the EIMS specific fixes just change that bool to true.

**Comment by marclaporte** [comment]
Last release of EIMS was in 2009.
