### ISSUE TITLE
Lifecycle, requirements/dependencies and Long Term Support (LTS) versions

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#431]
As of now, Cypht requires PHP 5.4:
https://packagist.org/packages/jason-munro/cypht#dev-master

The last release of PHP 5.4.x was 5 years ago: 
https://www.php.net/eol.php

Requirements/dependencies have an impact on our decisions as per:
https://github.com/jasonmunro/cypht/issues/429#issuecomment-694400048

Suggested reading: https://info.tiki.org/Versions

So what should our policy be for Cypht?

Thanks!

**Comment by jasonmunro** [comment]
I have considered dropping PHP 5.X support and likely will someday but not just yet. While I understand the reasoning behind LTS releases and a more formal release structure I just cannot commit to doing that for Cypht as I don't have the time.

**Comment by marclaporte** [comment]
ok, got it.

It is quite impressive that the same Cypht code base works from PHP 5.4 to PHP 7.4 
Ex.: https://github.com/jasonmunro/cypht/issues/405

This is a testament of great work done on Cypht **and** on PHP (the language itself)!

**Comment by marclaporte** [comment]
Fast forward 3+ years and we now have LTS versions: https://github.com/cypht-org/cypht/wiki/Lifecycle
