### ISSUE TITLE
Sent folder should show who message was sent to

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#433]
Right now, it shows my name on all messages.

![2020-06-11_123328](https://user-images.githubusercontent.com/1004261/93660217-6e9b8100-fa1a-11ea-99a8-bc7529fcdedd.png)

**Comment by jasonmunro** [comment]
I feel like this used to be correct and was reverted somehow. Anyway I agree and will fix.

**Comment by marclaporte** [comment]
Works well now.
