### ISSUE TITLE
After an action on an email, go to view mode of next email instead of list of emails

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#435]
My workflow is to go through all messages and do various actions (delete, archive, reply, etc.)

After I read and delete a message, it takes me back to the list. I'd like an option to view next message instead. I realize this can be tricky because the previous interface was possibly a search, or a list of emails coming from various accounts.

**Comment by Yamakasi** [comment]
I don't see it as a feature with a lot value.

Maybe change your workflow ;)

**Comment by marclaporte** [comment]
AFAIK, this is the default (an perhaps only) behavior in Roundcube/Kolab. And an option in Gmail.

![2020-09-25_202948](https://user-images.githubusercontent.com/1004261/94326431-d0f00680-ff71-11ea-8326-320bb2bb0532.png)

![Video_2020-09-25_204955](https://user-images.githubusercontent.com/1004261/94326428-ce8dac80-ff71-11ea-86e1-62e2c868600d.gif)

**Comment by marclaporte** [comment]
I fiddled with the settings. Not sure which one did it but now it sometimes works like I want but not always. I can delete or move a message, and then, see the next one. Then, I do the same thing, and I end up on the list. I don't know the pattern yet.

**Comment by marclaporte** [comment]
And now it's gone. I don't know what I did.

**Comment by marclaporte** [comment]
@josaphatim explained to me this has a link with the show previous/next message feature, that he made optional here:
https://github.com/jasonmunro/cypht/pull/588

**Comment by marclaporte** [comment]
Note to self: retest this after https://github.com/jasonmunro/cypht/pull/618

**Comment by marclaporte** [comment]
This should be done: https://github.com/jasonmunro/cypht/pull/603 but it doesn't work for me.
