### ISSUE TITLE
The "Stay logged in" checkbox on the login screen is not keyboard accessible

### ISSUE THREAD

**Issue by richardneish** [jasonmunro/cypht#437]
## 🐛 Bugreport
When I open the Cypht URL and I am not logged in, I see a login form with fields for "Username" and "Password", a checkbox labelled "Stay logged in" and a "Login" button.  The tab key moves from field to field as expected, but the space bar does not toggle the "Stay logged in" checkbox as expected.  This keyboard pattern works with checkboxes on other web sites.

### Version & Environment

Rev: ae6bf16ef4a31562699f2db11840d0d7a673a2a4

OS:  Ubuntu, web browser is Firefox 80.0.1

### Steps to reproduce
1. Go to Cypht URL as a logged out user
2. Use the tab key until the "Stay logged in" checkbox is highlighted
3. Press the space bar.  It is expected that the checkbox toggles between checked and unchecked, but this does not happen

**Comment by richardneish** [comment]
Might be related/similar to https://github.com/vuetifyjs/vuetify/issues/4627

**Comment by kk6mrp** [comment]
That's odd, I can not reproduce the issue on Firefox 81 and Chrome 85 on Windows. I'll have to try it out on Linux when I get back to my computer later.

**Comment by richardneish** [comment]
Ah, apologies - it looks like this is on my side, if I disable Evernote Web Clipper it works as expected.  Not sure if this is a known issue with Evernote, but it's not a Cypht issue.
