### ISSUE TITLE
Should Cypht show the dates/times in user's time zone?

### ISSUE THREAD

**Issue by marclaporte** [jasonmunro/cypht#444]
For a message, I see: Date | Mon, 26 Oct 2020 20:31:35 +0000

Would be more friendly to show in my time zone. But time zones can be tricky, especially with DST.

Thoughts?

**Comment by dumblob** [comment]
I think the default should be UTC. I'm though not opposed to some additional **opt-in** configurable behavior like showing the current (guessed!) time zone etc.

**Comment by marclaporte** [comment]
So maybe while we are at it, we have three options:
* guessed time zone
* time ago (like now)
* UTC time

**Comment by jasonmunro** [comment]
we have a timezone setting that if unset defaults to utc. IMO we should just use that (and include time ago in addition to the timestamp).

**Comment by jasonmunro** [comment]
@marclaporte check out the latest master and let me know what you think. Don't forget to set your timezone in the general settings.

**Comment by marclaporte** [comment]
@jasonmunro I confirm it works beautifully. Thanks!
