### ISSUE TITLE
POP3 implementation needs optional TOP command

### ISSUE THREAD

**Issue by jduepmeier** [jasonmunro/cypht#448]
## 🐛 Bugreport

The msg_headers function in the POP3 implementation needs the TOP command to receive the headers.
This command is optional (https://tools.ietf.org/html/rfc1939#page-11) and not every POP3 server implements it.
It should be checked if the server supports the TOP command. If not present the RETR command should get the headers.

### Version & Environment

Rev: 9363fc988aa424ae475a52ebae1a6c34f3cec7b9 (current master)

OS:  debian 10 with php 7.3

### Steps to reproduce
1. Configure a pop3 server which does not support the TOP command (for example https://github.com/cmail-mta/cmail)
2. Open Emails -> <pop3 server name>
3. Mail list will not load (runs in timeout)

**Comment by marclaporte** [comment]
Proposal: Deprecate POP3 support if no one steps up to maintain it
https://github.com/jasonmunro/cypht/issues/452
