### ISSUE TITLE
Calls HTMLPurifier_Language_en_x_test && Html2Text Skipped on Composer Install

### ISSUE THREAD

**Issue by cptsanifair** [jasonmunro/cypht#451]
💬 Question
In Version 1.2 on Composer Install it skips 2 Classes on autoload genereation in case of missig psr-4 compatibility.
Are there any Problems without?
(I ask befor long search because try to install for long term test as local mail client replacement)

CLI:
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 6 installs, 0 updates, 0 removals
  - Downloading christian-riesen/base32 (1.3.2)
  - Downloading codeitnowin/barcode (3.0.3)
  - Downloading erusev/parsedown (1.8.0-beta-5)
  - Downloading ezyang/htmlpurifier (v4.10.0)
  - Downloading html2text/html2text (4.2.1)
  - Downloading paragonie/random_compat (v2.0.18)
  - Installing christian-riesen/base32 (1.3.2): Extracting archive
  - Installing codeitnowin/barcode (3.0.3): Extracting archive
  - Installing erusev/parsedown (1.8.0-beta-5): Extracting archive
  - Installing ezyang/htmlpurifier (v4.10.0): Extracting archive
  - Installing html2text/html2text (4.2.1): Extracting archive
  - Installing paragonie/random_compat (v2.0.18): Extracting archive
Generating optimized autoload files
Class Html2Text\StrToUpperTest located in ./vendor/html2text/html2text/test/HeaderTest.php does not comply with psr-4 autoloading standard. Skipping.
Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. Skipping.

**Comment by jasonmunro** [comment]
We don't use HTMLPurifier unit tests so there is no concern here.

**Comment by cptsanifair** [comment]
after an update of composer.lock this msg doesnt shown again

**Comment by jasonmunro** [comment]
Appreciate the feedback but closing since it went away and was not an issue with Cypht. Thanks!
