### ISSUE TITLE
Cypht doesn't detect my Drafts folder

### ISSUE THREAD

**Issue by neildarlow** [jasonmunro/cypht#465]
## 🐛 Bugreport

RFC6154 describes a method for determining Special Folders assigned with Special Use flags.

I am using Dovecot and have set a folder **Drafts** with the Special Use flag of \Drafts. The Folder Settings page
doesn't display the ability to assign my Drafts folder although the code suggests it should.

Is it the case that the Drafts folder name is checked-for/set using a hard-coded value? I see it referred to in code as **'draft'**.

### Version & Environment

Rev: [1accf48] - master branch

OS:  [archlinuxARM/PHP-8.0.3]

### Steps to reproduce
1. Navigate to Folder Settings page.
2. Select IMAP server
3. Note that the page doesn't display a means to assign the **Drafts** folder which does exist.

**Comment by henrique-borba** [comment]
@neildarlow I'm solving the IMAP Draft support in https://github.com/jasonmunro/cypht/pull/464

It won't take long 🙂

**Comment by neildarlow** [comment]
@henrique-borba Thank you for this. I hope I can find out what's going on with JavaScript on my PHP-8.0.3 setup so I can test your fix.

**Comment by henrique-borba** [comment]
> @henrique-borba Thank you for this. I hope I can find out what's going on with JavaScript on my PHP-8.0.3 setup so I can test your fix.

What's the problem with the Javascript? Please also tell me your browser and version.

You are more than welcome 😃

**Comment by marclaporte** [comment]
yay, we found one more tester for the upcoming draft feature :-)

**Comment by neildarlow** [comment]
Tested. Partially working?

You can select the server and assign folders but they don't persist over logout and login. Nottifcation shows folder assigned.

That is, however, some progress.

**Comment by jasonmunro** [comment]
@neildarlow nothing persists between logins unless you explicitly save your settings first. I just tested to make sure and it worked fine as long as I go to Settings -> Save.

**Comment by neildarlow** [comment]
Doh, of course!

That was a really simple fix. ;-)

**Comment by jasonmunro** [comment]
Good point it did not. Because of how that page works we need 1 full refresh to enable the prompt on logout. I will see if that can be improved :). Thanks for the report and feedback!

**Comment by marclaporte** [comment]
@neildarlow Please test https://github.com/jasonmunro/cypht/pull/464

**Comment by henrique-borba** [comment]
I think https://github.com/jasonmunro/cypht/pull/474 solved this issue

**Comment by neildarlow** [comment]
I thin we can close this issue as fixed. Special folders handling has been addressed.
