### ISSUE TITLE
Login button is not button-like (mouse does not indicate it can be clicked, and clicking it does nothing visible)

### ISSUE THREAD

**Issue by gitcnd** [jasonmunro/cypht#486]
## 🗣 Suggestion

1. Let the mouse be normal for a button (change to a hand instead of an arrow)
2. Do something when it is clicked - it is probably AJAX I guess, because the browser does not indicate that it's loading any resource or generally "doing anything" when clicked.

**Comment by jasonmunro** [comment]
The login page has no JavaScript (unless you enable reCaptcha) and the button is a standard submit input element. you are right it does not look clickable so I will fix that.

Not sure what you mean by it's not doing anything (?) I think it might just be failing very quickly and not showing the proper notice on failure (as you mention in the other issue) so it appears to be doing nothing. It is just a normal HTML submit element so as long as the 2 required fields are filled out it will submit the form over standard HTTP(S). If the 2 required fields (username and password) are not filled out it is up to the browser to handle the interaction WRT required fields.

**Comment by gitcnd** [comment]
Weird - I'll do a screencast if it happens again - my box is on the other side of the world, so how I could have missed any kind of browser feedback to a form submit I don't know!  (I repeated it several times)...

The CSS definitely needs a tweak - normal default buttons change on mouseover, look like buttons, and also change when clicked - you somehow made your button look like an input box, with no change or action on mouseover or click - but that's just nitpicky of course - the main problem is the "no error showing" when errors were encountered.

**Comment by jasonmunro** [comment]
I must have a blanket css rule that is disrupting the default pointer for buttons so I just added it directly to the login button and now it behaves the way one expects. I agree the main problem is the missing error message so I'm going to fix that and follow up on that issue and close this one. Thanks for the feedback!
