### ISSUE TITLE
The logic of installation flow seems broken

### ISSUE THREAD

**Issue by jasongitaccount** [jasonmunro/cypht#488]
Edit: the problem was that I confused the authentication settings with user settings. It seems like my logic is broken! 

_If you follow the installation guidelines at "https://cypht.org/install.html" and go with the **default configuration** that stores user settings in the **filesystem**, in step 5 you will learn that **there is no instructions** for setting users in the filesystem. Instead it explains how to manage users if you have configured a **DB storage**._

**Comment by jasonmunro** [comment]
@jasongitaccount no worries and sorry for the confusion. Our docs pretty much suck for the most part :) Appreciate the feedback and glad you got it sorted out.
