### ISSUE TITLE
showing only Unsaved changes

### ISSUE THREAD

**Issue by omaisali** [jasonmunro/cypht#496]
## 🐛 Bugreport
I have config everything, after login it show this.  Any help please
![image](https://user-images.githubusercontent.com/475740/124174237-8df52d80-dac5-11eb-84b9-8dd7f0b31276.png)

### Version & Environment
Php 7.4, Laragon

**Comment by jasonmunro** [comment]
I think this was resolved via re-install, @omaisali can you confirm if you still have a problem or close this? thanks!

**Comment by marclaporte** [comment]
@omaisali Closing as out of date. Please re-open if issue persists.
