### ISSUE TITLE
Pop-up errors are not translated

### ISSUE THREAD

**Issue by Revisto** [jasonmunro/cypht#500]
## 🐛 Bugreport

Pop-up errors are not translated to the user's language.
![image](https://user-images.githubusercontent.com/60847212/125484365-c659acb0-78c1-4d55-9b05-e8ca8166babc.png)

**Comment by marclaporte** [comment]
@jasonmunro Do you have a roadmap or ideas on this, or would you like a proposal?

Thanks!

**Comment by jasonmunro** [comment]
We have a translation system and messages like this are run through it already - we just need the phrase to be added to the language files and actually translated :)
