### ISSUE TITLE
codeitnowin/barcode 3.0.5 requires ext-gd * -> the requested PHP extension gd is missing from your system.

### ISSUE THREAD

**Issue by jeremiah** [jasonmunro/cypht#516]
## 🐛 Bugreport
Running `composer install` in cypht-temp/cypht-master/ produces an error. This prevents the installation of cypht.
I see that ext-gd is listed in the install page but it's only listed as "suggests" in composer.json.

### Version & Environment
Debian 10, php 7.3

### Steps to reproduce
1. cd cypht-temp/cypht-master/
2. composer install
```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for codeitnowin/barcode 3.0.5 -> satisfiable by codeitnowin/barcode[3.0.5].
    - codeitnowin/barcode 3.0.5 requires ext-gd * -> the requested PHP extension gd is missing from your system.
```

**Comment by jeremiah** [comment]
Installing php-gd fixes this error on my system.

**Comment by jasonmunro** [comment]
yep, the gd requirement should be moved. Thanks for the feedback!

**Comment by marclaporte** [comment]
AFAICT, this is only used for https://github.com/jasonmunro/cypht/blob/master/modules/2fa/modules.php which is not a central feature.

Idea: 
1. Make ext-gd a suggestion in the installer 
2. Have a friendly error message on attempt to use feature with missing dependency

**Comment by jeremiah** [comment]
Good point @marclaporte I've forgotten what error message I saw but I felt (at least at the time) that I couldn't install without ext-gd. I saw that it was used for images which is a pretty standard feature if web mail so I thought I ought to install it anyway. I think your approach is the right one.

**Comment by neildarlow** [comment]
I'd like to see the need for the GD extension to be optional. I have a patch which modifies composer.json and composer.lock to remove this dependency so I don't have to install it.

**Comment by jeremiah** [comment]
I have a plan to test the installation of cypht on the new version of Debian. I'll review that bug as part of that work.

**Comment by ElvisAns** [comment]
Hi , i am affraid but the Qr code library we are using requires Imagick extension to run properly....

**Comment by ElvisAns** [comment]
GD is so then no longer needed ...

**Comment by ElvisAns** [comment]
@jeremiah we have moved to bacon/bacon-qr-code for QR code generation as codeitnowin/barcode reached the end life support. Please check on https://github.com/jasonmunro/cypht/issues/562

**Comment by jeremiah** [comment]
I would love to test this out and update my cypht install at the same time. I'm traveling at the moment and will be back towards the end of next week.

**Comment by ElvisAns** [comment]
Great 👍
