### ISSUE TITLE
Cypth Multiarch Docker Image for arm64 arm/v8 arm/v7 arm/v6 for Raspberry Pi

### ISSUE THREAD

**Issue by x0tester0x** [jasonmunro/cypht#539]
The docker images should be expanded to support also arm architectures.

**Comment by x0tester0x** [comment]
I want to use the Docker Image on an Raspberry Pi 4 (armv8) can you please provide such an Image?

**Comment by marclaporte** [comment]
Closing as duplicate: https://github.com/jasonmunro/cypht-docker/issues/16
