### ISSUE TITLE
Code Doc site shows 403 forbidden

### ISSUE THREAD

**Issue by rhclayto** [jasonmunro/cypht#542]
## 💬 Question

All links to code documentation site brings up a 403 Forbidden error.

**Comment by marclaporte** [comment]
URL?

**Comment by kk6mrp** [comment]
I think he is referring to the code documentation links located at `?page=info`.

**Comment by rhclayto** [comment]
https://cypht.org/docs/code_docs/index.html

& all others at that subpath.

**Comment by jasonmunro** [comment]
Should be fixed. Sorry about that had a bit of a space issue on the server!
