### ISSUE TITLE
Search impacting unread combined view

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#554]
- Do a search
- Go to the combined unread page

it will filter out anything not matching the search terms. Search should only impact the search results page (this is the main search bar on the left not the inline search option on an IMAP folder view).

@marclaporte I think one of the recent PRs introduced this issue do you have anyone who can check into it? Thanks!

**Comment by jasonmunro** [comment]
fixed in master

**Comment by marclaporte** [comment]
Sorry we didn't fix. @jeanpaulHamuli was unable to reproduce issue locally.

**Comment by jeanpaulHamuli** [comment]
Yes, we are sorry @jasonmunro, I was ready to work on it unfortunately I could not reproduce the issue
