### ISSUE TITLE
codeitnow barcode generator not available

### ISSUE THREAD

**Issue by sierracircle** [jasonmunro/cypht#562]
Hi. Running composer install gives me:
`Failed to download codeitnowin/barcode from dist: The "https://api.github.com/repos/codeitnowin/barcode-generator/zipball/bd140d279fc813e00f72eaa4f033186bf78b8786" file could not be downloaded (HTTP/1.1 451 Unavailable for Legal Reasons)`

Looking at the github page for them, there is a DMCA takedown notice.

Removing the codeitnow from line 27 of the composer.json   seems to work for now.
Not sure what the barcode-generator thing is for. I have no need of it.

**Comment by marclaporte** [comment]
For the record: https://github.com/github/dmca/blob/master/2022/04/2022-04-20-barcodebakery.md

**Comment by marclaporte** [comment]
Here is why/when it was introduced: https://github.com/jasonmunro/cypht/commit/6eba0485514114b1573792dbd9bceecf184498d4

**Comment by ElvisAns** [comment]
So.. the api is ready to be called in case we just want to generate a barcode with cypht? 2D barcode preferably

**Comment by marclaporte** [comment]
@ElvisAns Can you make a merge request to resolve this? Go back to previous lib or propose a another one.

Thanks!

**Comment by ElvisAns** [comment]
Well i walk through it and do something ASAP

**Comment by jasonmunro** [comment]
We should probably just revert to the original QR code generating library.

**Comment by ElvisAns** [comment]
I have also got the error
`
Failed to download codeitnowin/barcode from dist: The "https://api.github.com/repos/codeitnowin/barcode-generator/zipball/bd140d279fc813e00f72eaa4f033186bf78b8786" file could not be downloaded (HTTP/2 451 ):
{"message":"Repository access blocked","block":{"reason":"dmca","created_at":"2022-04-20T23:29:58Z","html_url":"https://github.com/github/dmca/blob/master/2022/04/2022-04-20-barcodebakery.md"}}
    Now trying to download from source`

after running 
`
composer install
`
As @jasonmunro said it seems like we need to replace this dependency!

**Comment by ElvisAns** [comment]
And packagist has the answer **_"This package is abandoned and no longer maintained. The author suggests using the [barcode-bakery/barcode-1d](https://packagist.org/packages/barcode-bakery/barcode-1d) package instead."_**
https://packagist.org/packages/codeitnowin/barcode

**Comment by ElvisAns** [comment]
I have made something at [this pull request](https://github.com/jasonmunro/cypht/pull/566), 

Test results are welcome!

**Comment by jasonmunro** [comment]
@ElvisAns this looks great thanks for doing this. I was just looking into doing the exact same thing :) I will merge this today
