### ISSUE TITLE
mispelling

### ISSUE THREAD

**Issue by sierracircle** [jasonmunro/cypht#563]
On the "Everything" page, with just a few items, a notice appears at the bottom of the page that says:

"There is no pagination is this view, please visit the individual mail boxes."

is  should be  in, or perhaps "..in this here view,.."

**Comment by marclaporte** [comment]
Good catch!

Here is the code:
https://github.com/jasonmunro/cypht/blob/master/modules/imap/output_modules.php#L724

@sierracircle Ready to make your first merge request on the project? You can use the GitHub web interface.

Thanks!

**Comment by marclaporte** [comment]
Thank you @sierracircle 
https://github.com/jasonmunro/cypht/pull/564
