### ISSUE TITLE
When sending an email with an attached file, only the text of the email arrives to the recipient and not the attached file

### ISSUE THREAD

**Issue by NasserNgandu** [jasonmunro/cypht#567]
When sending an email with an attached file. the recipient only receives the text of the email, the attached file disappears. It does not appear on the sender or on the recipient.

**Comment by marclaporte** [comment]
Related: https://github.com/jasonmunro/cypht/issues/421

**Comment by marclaporte** [comment]
Possible fix: https://github.com/jasonmunro/cypht/pull/575
