### ISSUE TITLE
Drag and drop reordering of recipients (to / cc / bcc) with balloons/bubbles

### ISSUE THREAD

**Issue by nekohayo** [jasonmunro/cypht#577]
Basically the same idea as what I'm proposing there ;) https://gitlab.gnome.org/GNOME/evolution/-/issues/1967
This facilitates good email netiquette.

This behavior can be seen in Thunderbird, GMail, Apple Mail, Horde (of all things!), and probably others.

**Comment by marclaporte** [comment]
Related: https://github.com/jasonmunro/cypht/issues/216
