### ISSUE TITLE
Composer lockfile problem

### ISSUE THREAD

**Issue by ksieluzycki** [jasonmunro/cypht#628]
Hello,

During installation I encountered following error from composer install:

No vendor dir present, checking platform requirements from the lock file
In Locker.php line 324:
  [LogicException]                                   
  No lockfile found. Unable to read locked packages  

I thought it should create composer lock if necessary, but it didn't. I also tried composer update, but it also shows same error and does not create composer lock.

It looks like check-platform-reqs is invoked as pre-command and it requires composer lock. I just edited composer.json:

    "scripts": {
        "pre-install-cmd":  "",
        "pre-update-cmd": "",

After that composer install completed succesfully. 

Tested on:
Composer version 2.4.2 2022-09-14 16:11:15
on Debian 11.5 and on Artix

Regards,
Krzysztof

**Comment by jasonmunro** [comment]
Appreciate the feedback. We have been discussing removing this from the composer.json file as I ran into the same issue. In my case I had scripted an update process that was calling composer as root. Once I modified that it started working even with the check-platform-reqs active.

**Comment by ElvisAns** [comment]
https://github.com/jasonmunro/cypht/pull/632/

**Comment by marclaporte** [comment]
Closing in favor of:
- https://github.com/jasonmunro/cypht/pull/632
- https://github.com/jasonmunro/cypht/issues/597
