### ISSUE TITLE
CardDAV contacts module does not work

### ISSUE THREAD

**Issue by robert-winkler** [jasonmunro/cypht#640]
Hi, I installed the Cypht master of 2022/10/13 on an Ubuntu 20.04 LTS web server.
I would like to use my 1,000+ CardDAV contacts that are hosted on a different NextCloud server.
Thus, I 
- enabled the modules 'contacts' and 'contacts_carddav' in the hm3.ini
- copied the carddav.ini to the app_data directory, renamed the [Personal] to [CardDAV NextCloud] and added http of my CardDAV server (the exact address, without port, works e.g. with vdirsyncer).
- run PHP ./scripts/config-gen.php
- login to Cypht.
- in contacts, I can see the error: "No contact backends are enabled!
At least one backend must be enabled in the hm3.ini file to use contacts.", However, I have the option to add contacts to the [Contacts NextCloud] 
- In Settings, I found the section CardDAV; added username and password, save the settings and site settings, log out and log in; same symptoms.

I have the impression, there are 2 different problems:

- The check for a valid backend fails, if there is no local, LDAP or Gmail backend (CardDAV is not in the checked backends?)
- The connection to the CardDAV server fails. Is there any way to find out the reason (http or user validation)?

**Comment by marclaporte** [comment]
Related: https://github.com/jasonmunro/cypht/issues/120

**Comment by marclaporte** [comment]
Related discussion: https://gitter.im/cypht-org/community?at=636403d45b0dbc04b8b41123

**Comment by marclaporte** [comment]
@ElvisAns will work on this.

**Comment by ElvisAns** [comment]
I'm working on it. 

Hope we fix it soon. Stay tuned!

The original thread about the integration : https://github.com/jasonmunro/cypht/issues/120

**Comment by marclaporte** [comment]
@robert-winkler Please test

**Comment by ElvisAns** [comment]
Please see the following video : https://app.flonnect.com/view/video/ansimapersic/Flonnect_2023-02-18_173c3c94-4107-4c30-9d9d-6a5c9a3b208e

**Comment by robert-winkler** [comment]
Dear @ElvisAns and @marclaporte, I watched the video twice, but it only shows the client side (the user's web interface). What do I need to do on the server? Changing any .PHP files; install a new version of Cypht? How do I have to configure the CardDAV connection?

**Comment by marclaporte** [comment]
@robert-winkler Please change PHP files as per https://github.com/jasonmunro/cypht/pull/674/files

**Comment by robert-winkler** [comment]
Dear @marclaporte and @ElvisAns:
Yes, with the modified PHP I can see my NextCloud CardDAV server.
 
![carddav](https://user-images.githubusercontent.com/9994605/221969291-07fbdfef-5d14-4c04-940a-718b50e1bb2e.png)

I still got two problems:

1) How do I authenticate to my server?

I added to the `carddav.ini`:
~~~
server="https://server.org/...contacts/"
user="Robert"
pass="A very long password"
~~~

2) Cypht complains about a missing contacts module.

But my `hm3.ini` contains:
~~~
modules[]=contacts
modules[]=carddav_contacts
~~~

of course, I could uncomment the local_contacts, but just carddav_contacts should be sufficient.

**Comment by ElvisAns** [comment]
@robert-winkler it's still complaining because your enabled contact backend is not yet authenticated.

**Comment by ElvisAns** [comment]
Go to Site Settings and the put your username / password under the `Carddav Adressbooks` section and hit save.
Dont forget to read https://github.com/jasonmunro/cypht/pull/674#issue-1590316401
