### ISSUE TITLE
How can I as admin add/remove users using UI?

### ISSUE THREAD

**Issue by undergroundwires** [jasonmunro/cypht#664]
## 💬 Question

I have account module enabled and use DB authentication as documented. I'm using admin user created by Docker image.

I checked all settings, I cannot find a place in UI to manage users. I tried all keywords I come with and search for an example but could not find any documentation.

How can I as admin manage users using UI (not scripts)?

**Comment by undergroundwires** [comment]
After some debugging I found out that I need to add my user to `CYPHT_ADMIN_USERS`, this should probably be default in the docker compose file.

**Comment by kk6mrp** [comment]
Also, if you take a look on the website at https://cypht.org/install.html, it states the following for managing users:

> 5. Users
> Setting up users depends on what type of authentication you configure in the hm3.ini file. If you are using the local database configuration for users, there are scripts in the scripts/ directory to help manage them:

``` bash 
# create an account
php ./scripts/create_account.php username password

# delete an account
php ./scripts/delete_account.php username

# change an account password
php ./scripts/update_password.php username password
```
