### ISSUE TITLE
Images aren't loaded if message is shown "inline"

### ISSUE THREAD

**Issue by Magneticdud** [jasonmunro/cypht#719]
## 🐛 Bugreport
If show the message inline, it's not possible to load external images in email

### Version & Environment
[dd67951](https://github.com/jasonmunro/cypht/commit/dd67951b42de854fcd0c12b86b62868e84712f90)

OS:  Alpine linux + PHP 7.4

### Steps to reproduce
1. open a message inline that uses remote images (example with some spam:)

https://github.com/jasonmunro/cypht/assets/2940598/45d1da90-c466-4daa-8bfb-5e8396aac276

images aren't loaded

instead, if the message is opened full screen, they are loaded (example with the same spam:)

https://github.com/jasonmunro/cypht/assets/2940598/6de91887-0886-4321-89d7-a40f2bffadcb

**Comment by jasonmunro** [comment]
Not surprised by this. The inline message view code is pretty hacky (I can say that since I wrote it). It could use a rewrite! (ping @marclaporte)

**Comment by marclaporte** [comment]
ok, we'll put on the roadmap!

**Comment by josaphatim** [comment]
> ## 🐛 Bugreport
> If show the message inline, it's not possible to load external images in email
> 
> ### Version & Environment
> [dd67951](https://github.com/jasonmunro/cypht/commit/dd67951b42de854fcd0c12b86b62868e84712f90)
> 
> OS: Alpine linux + PHP 7.4
> 
> ### Steps to reproduce
> 1. open a message inline that uses remote images (example with some spam:)
> 
>  no.images.mp4 
> images aren't loaded
> 
> instead, if the message is opened full screen, they are loaded (example with the same spam:)
> 
>  images.mp4

Hello @Magneticdud
I don't have such message in my spam to reproduce. Can you forward this to test@notre.website if possible ?
Thanks.

**Comment by Magneticdud** [comment]
I'm not finding an email with remote images that at the same time doesn't contain personal info, if i find, i will forward. Domain is cypht . org?

by the way, it's about any email with remote images
